---
# Frontend certs
api_ssl_pem:      "api.%{hiera('domain_frontend')}.pem"
status_ssl_pem:   "status.%{hiera('domain_frontend')}.pem"
# Location only certs
star_api_ssl_pem: "star.api.%{hiera('domain_public')}.pem"

identity__backend__names:
  - "%{::location}-identity-01"
  - "%{::location}-identity-02"
identity__backend__ips:
  - "%{hiera('netcfg_trp_netpart')}.81"
  - "%{hiera('netcfg_trp_netpart')}.82"
