---
named_interfaces::config:
  mgmt:
    - br0
  trp:
    - br1
  transport:
    - br1
  service:
    - br1

# Turn off bird on controller until we use cumulus
profile::openstack::network::calico::manage_bird: false

himlar_bootstrap::virt_install:
  '%{location}-admin-01':
    domain:          '%{domain}'
    libvirt_pool:    'dirpool'
    libvirt_network: 'directnet'
    install_ip:      "%{hiera('netcfg_mgmt_netpart')}.11"
    install_netmask: "%{hiera('netcfg_mgmt_netmask')}"
    install_gateway: "%{hiera('netcfg_mgmt_gateway')}"
    vm_vcpus:        1
    vm_memory:       2048
    vm_console:      false
