---
include:
  default:
    - profile::monitoring::netdata

named_interfaces::config:
  mgmt:
  - eth2
  trp:
  - team1
  live:
  - team1.120

profile::base::network::network_auto_bonding:
  trp:
    eth0:
      'team_port_config': '{ "prio" : 100 }'
    eth1:
      'team_port_config': '{ "prio" : 100 }'

# Turn off nested virtualization
profile::virtualization::nested::manage: false

# Enable hugepages to prevent OOM-killer when using NUMA
profile::base::physical::enable_hugepages: true
# Number and size of hugepages, based on 512GB - 32 GB (4GB free pr node)
profile::base::physical::hugepagesz:       '2M'
profile::base::physical::hugepages:        '245760'

profile::monitoring::netdata::manage_firewall: true

# Nover overrides
nova::compute::libvirt::libvirt_cpu_model: 'EPYC'
nova::cpu_allocation_ratio:                '1'

# Create and enable more swap
profile::base::common::extraswap:        true
profile::base::common::extraswap_sizegb: 10

profile::base::lvm::physical_volume:
  '/dev/sda3':
    ensure: present
    force:  true
profile::base::lvm::volume_group:
  'vg_ext':
    physical_volumes:
      - /dev/sda3
profile::base::lvm::logical_volume:
  'lv_instances':
    volume_group: 'vg_ext'
    fs_type:      "xfs"
    mountpath:    "/var/lib/nova/instances"

sensu__memory__check:     "check-memory.rb -w 1536 -c 1024"

# This compute host uses local storage for instances
nova::compute::rbd::ephemeral_storage:  false
nova::config::nova_config:
  libvirt/images_type:
    value: default
  DEFAULT/metadata_workers:
    value: '2'
