---
named_interfaces::config:
  mgmt:
    - em1
  trp:
    - team1
  live:
    - team1.120

profile::base::network::network_auto_bonding:
  trp:
    em3:
      'team_port_config': '{ "prio" : 100 }'
    em4:
      'team_port_config': '{ "prio" : 100 }'
