---
# Designate pools.yaml definitions
profile::openstack::designate::bind_servers:
  'osl-01':
    ns_rndc_addr:    '2001:700:2:82ff::251'
    ns_public_addr:  '2001:700:2:82ff::251'
    ns_public_name:  "%{hiera('profile::dns::ns::ns_master1')}"
    mdns_addr:
      - '2001:700:2:82ff::256'
      - '2001:700:2:83ff::256'
  'bgo-01':
    ns_rndc_addr:    '2001:700:2:83ff::251'
    ns_public_addr:  '2001:700:2:83ff::251'
    ns_public_name:  "%{hiera('profile::dns::ns::ns_master2')}"
    mdns_addr:
      - '2001:700:2:82ff::256'
      - '2001:700:2:83ff::256'

# Firewall configuration
profile::openstack::designate::ns_sources_ipv6:
  - '2001:700:2:82ff::251'
  - '2001:700:2:83ff::251'
