---
# disks
profile::base::common::manage_lvm: true

profile::base::lvm::physical_volume:
  '/dev/vdb':
    ensure: present
    force:  true
profile::base::lvm::volume_group:
  'vg_metric':
    physical_volumes:
      - /dev/vdb
profile::base::lvm::logical_volume:
  'lv_gnocchi':
    volume_group: 'vg_metric'
    fs_type:      "xfs"
    mountpath:    "/var/lib/gnocchi"
    size:         '19.9G'

