---
profile::monitoring::sensu::server::handlers:
  slack:
    type:           'pipe'
    command:        'handler-slack.rb'
    filters:
      - normal
      - infrequent
    config:
      webhook_url:  "%{hiera('sensu_slack_webhook')}"
      channel:      '#vakt'
    severities:
      - 'ok'
      - 'critical'
      - 'unknown'
