---
# Authoritative name servers must have a public interface 
profile::base::network::manage_dummy: true

# Public and internal zones
profile::dns::ns::internal_zone: "osl.uhdc.no"
profile::dns::ns::public_zone:   "osl.uh-iaas.no"
profile::dns::ns::frontend_zone: "uh-iaas.no"

# Name servers in zone file
profile::dns::ns::ns_master: "ns.%{hiera('profile::dns::ns::public_zone')}"
#profile::dns::ns::ns_slaves:
#  - "ns.test.iaas.uio.no"

# Master server for master-slave configuration
#profile::dns::ns::ns_master_ip_addresses:
#  - "%{hiera('public__address__ns')}"  # local ns IPv4 address
#  - "%{hiera('public6__address__ns')}" # local ns IPv6 address

# Slave servers for master-slave configuration
#profile::dns::ns::ns_slave_ip_addresses:
#  - '192.168.0.251'         # ns.test.iaas.uio.no IPv4
#  - 'fc00:700:100:200::251' # ns.test.iaas.uio.no IPv6

# Forward zones, for which the name server is authoritative
profile::dns::ns::fw_zones:
  internal:
    zone: "%{hiera('profile::dns::ns::internal_zone')}"
    filename: "pz/%{hiera('profile::dns::ns::internal_zone')}"
  public:
    zone: "%{hiera('profile::dns::ns::public_zone')}"
    filename: "pz/%{hiera('profile::dns::ns::public_zone')}"
  frontend:
    zone: "%{hiera('profile::dns::ns::frontend_zone')}"
    filename: "pz/%{hiera('profile::dns::ns::frontend_zone')}"

# Reverse zones, for which the name server is authoritative
profile::dns::ns::ptr_zones:
  internal:
    cidr: "172.16.0.0/16"
    origin: "16.172.in-addr.arpa"
    filename: "pz/16.172.in-addr.arpa"
  public1:
    cidr: "158.37.0.0/16"
    origin: "37.158.in-addr.arpa"
    filename: "pz/37.158.in-addr.arpa"
  public2:
    cidr: "158.39.0.0/16"
    origin: "39.158.in-addr.arpa"
    filename: "pz/39.158.in-addr.arpa"
  ipv6:
    cidr: "2001:700:2:82ff::/64"
    origin: "f.f.2.8.0.0.7.0.2.0.0.0.1.0.0.2.ip6.arpa"
    filename: "pz/f.f.2.8.0.0.7.0.2.0.0.0.1.0.0.2.ip6.arpa"
