---
named_interfaces::config:
  mgmt:
    - em3
  trp:
    - team1
  ceph:
    - team1.110

profile::base::network::network_auto_opts:
  trp:
    'defroute': 'no'
    'devicetype': 'Team'
    'team_config': >-
                   { "runner" : {  "name" : "lacp",  "active": true, "fast_rate" : true,
                   "tx_hash": ["eth", "ipv4", "ipv6"], "tx_balancer": { "name": "basic" } },
                   "link_watch" : {  "name" : "ethtool" } }
  ceph:
    'defroute': 'no'

profile::storage::cephpool::manage_cephpool_params:  false

profile::base::physical::configure_bmc_nic:          true
profile::base::physical::enable_redfish_sensu_check: true
profile::monitoring::sensu::agent::checks:
  'redfish-check':
    command:      '/usr/local/bin/redfish_check.sh'
    interval:     1800
    subscribers:  ['checks']

profile::storage::ceph_crushrules::rules:
  'hdd-storage':
    rule_device_type: "hdd"
    rule_root:        "storage"
  'ssd-storage':
    rule_device_type: "sdd"
    rule_root:        "storage"
  'hdd-arccache':
    rule_device_type: "hdd"
    rule_root:        "arccache"
  'ssd-arccache':
    rule_device_type: "ssd"
    rule_root:        "arccache"

profile::storage::ceph::pool::pools:
  'rbd':
    ensure: absent
  'volumes':
    size:    3
    pg_num:  2048
    pgp_num: 2048
    tag:     'rbd'
    custom:
      crush_rule: 'hdd-storage'
      nodelete:   'true'
      min_size:   '2'
  'images':
    size:    3
    pg_num:  512
    pgp_num: 512
    tag:    'rbd'
    custom:
      crush_rule: 'hdd-storage'
      nodelete:   'true'
      min_size:   '2'
  'vms':
    size:    3
    pg_num:  256
    pgp_num: 256
    tag:     'rbd'
    custom:
      crush_rule: 'ssd-storage'
      nodelete:   'true'
      min_size:   '2'
  'volumes_hdd_ec_meta':
    size:    3
    pg_num:  256
    pgp_num: 256
    tag:     'rbd'
    custom:
      crush_rule: 'ssd-storage'
      nodelete:   'true'
      min_size:   '2'
profile::storage::ceph::pool::ec_pools:
  'placeholder':
    manage: false

profile::base::lvm::physical_volume:
  '/dev/sdi':
    ensure: present
    force:  true
profile::base::lvm::volume_group:
  'vg_cache':
    physical_volumes:
      - /dev/sdi
profile::base::lvm::logical_volume:
  'lv_wala':
    volume_group: 'vg_cache'
    createfs:     false
    size:         2G
  'lv_dba':
    volume_group: 'vg_cache'
    createfs:     false
    size:         10G
  'lv_walb':
    volume_group: 'vg_cache'
    createfs:     false
    size:         2G
  'lv_dbb':
    volume_group: 'vg_cache'
    createfs:     false
    size:         10G
  'lv_walc':
    volume_group: 'vg_cache'
    createfs:     false
    size:         2G
  'lv_dbc':
    volume_group: 'vg_cache'
    createfs:     false
    size:         10G
  'lv_wald':
    volume_group: 'vg_cache'
    createfs:     false
    size:         2G
  'lv_dbd':
    volume_group: 'vg_cache'
    createfs:     false
    size:         10G
  'lv_wale':
    volume_group: 'vg_cache'
    createfs:     false
    size:         2G
  'lv_dbe':
    volume_group: 'vg_cache'
    createfs:     false
    size:         10G

profile::storage::cephosd::osds:
  '/dev/sda':
    db_device:  'vg_cache/lv_dba'
    wal_device: 'vg_cache/lv_wala'
  '/dev/sdb':
    db_device:  'vg_cache/lv_dbb'
    wal_device: 'vg_cache/lv_walb'
  '/dev/sdc':
    db_device:  'vg_cache/lv_dbc'
    wal_device: 'vg_cache/lv_walc'
  '/dev/sdd':
    db_device:  'vg_cache/lv_dbd'
    wal_device: 'vg_cache/lv_wald'
  '/dev/sde':
    db_device:  'vg_cache/lv_dbe'
    wal_device: 'vg_cache/lv_wale'
  '/dev/sdf': {}
  '/dev/sdg': {}
  '/dev/sdh': {}
#  '/dev/sdi': {}
#  '/dev/sdj': {}
