---
named_interfaces::config:
  mgmt:
    - eno3
  transport:
    - team1
  trp:
    - team1
  ceph:
    - team1.110

profile::base::network::network_auto_opts:
  trp:
    'defroute': 'no'
    'devicetype': 'Team'
    'mtu': '9000'
    'team_config': >-
                   { "runner" : {  "name" : "lacp",  "active": true, "fast_rate" : true,
                   "tx_hash": ["eth", "ipv4", "ipv6"], "tx_balancer": { "name": "basic" } },
                   "link_watch" : {  "name" : "ethtool" } }
  ceph:
    'defroute': 'no'

profile::base::network::network_auto_bonding:
  trp:
    ens6f0:
      'team_port_config': '{ "prio" : 100 }'
      'mtu': '9000'
    ens6f1:
      'team_port_config': '{ "prio" : 100 }'
      'mtu': '9000'

# placeholder data - FIXME
profile::base::common::manage_lvm:           false
rofile::base::lvm::create_lvm:               false
profile::storage::cephpool::manage_ec_pools: false
profile::storage::cephosd::create_osds:      false
profile::storage::cephosd::crush_move:       false
