---
include:
  default:
    - profile::application::access
    - profile::webserver::apache
    - profile::openstack::openrc

# Read only admin user
profile::openstack::openrc::username:         'access'
profile::openstack::openrc::password:         "%{hiera('access_api_password')}"
profile::openstack::openrc::project_name:     'services'

profile::base::network::manage_dummy:           true
profile::webserver::apache::manage_firewall:    false
profile::application::access::manage_firewall:  true
profile::application::access::package_url:      'https://download.iaas.uio.no/uh-iaas/rpm/himlar-dp-prep-1.5-3.el7.x86_64.rpm'
dpapp::installdir:        '/opt/dpapp'

profile::application::access::firewall_extras:
  source: "%{::network_trp1}/%{::netmask_trp1}"

apache::default_mods:   false
profile::webserver::apache::mods_enable:
  - wsgi
  - dir

profile::base::common::packages:
  'bash-completion': {}
  'bash-completion-extras': {}
  'jq': {}
  'python-openstackclient': {}

profile::webserver::apache::vhosts:
  dpapp:
    vhost_name:         "%{hostname}.%{hiera('domain_trp')}"
    servername:         "%{hostname}.%{hiera('domain_trp')}"
    serveraliases:
     - "%{hiera('public__address__access')}"
     - "access-%{::location}.%{hiera('domain_frontend')}"
    port:               '80'
    manage_docroot:     false
    docroot:            '/var/www/html'
    wsgi_application_group:  '%%{}{GLOBAL}'
    wsgi_pass_authorization: 'on'
    wsgi_daemon_process:     'dpapp'
    wsgi_daemon_process_options:
      threads:      '4'
      python-path:  "%{hiera('dpapp::installdir')}/lib/python2.7/site-packages"
    wsgi_script_aliases:
      '/':   "%{hiera('dpapp::installdir')}/pyramid.wsgi"
    directories:
      - path:             "%{hiera('dpapp::installdir')}"
        require:          'all granted'
        custom_fragment:  'WSGIProcessGroup dpapp'

# RDO used for openstackclient
profile::base::yumrepo::repo_hash:
  rdo-release:
    ensure: present
