---
include:
  default:
    - profile::application::foreman
    - profile::database::postgresql
    - profile::network::services
    - profile::webserver::apache

foreman_version: '1.14'

profile::base::common::packages:
  'bash-completion': {}
  'bash-completion-extras': {}
  'jq': {}

profile::application::foreman::manage_eyaml:    false
profile::application::foreman::manage_firewall: true
profile::application::foreman::manage_repo_dir: true
profile::application::foreman::manage_r10k:     true
profile::network::services::manage_dns_records: true
profile::network::services::manage_dhcp_rsvs:   true

# We need SCL repos
openstack_extras::repo::redhat::redhat::purge_unmanaged:  false

puppet::server:                        true
puppet::server_foreman_url:            "https://%{hiera('mgmt__address__foreman')}"
puppet::dns_alt_names:
  - "puppet.%{hiera('domain_mgmt')}"
  - "puppetca.%{hiera('domain_mgmt')}"
  - "admin.%{hiera('domain_mgmt')}"

profile::webserver::apache::manage_firewall:  false
profile::webserver::apache::vhosts:
  'repo':
    servername:     "%{hiera('mgmt__address__repo')}"
    port:           80
    docroot:        '/opt/repo/public'
    docroot_owner:  'iaas'

dhcp::onie_inst_def_url:     "http://repo.%{domain}/cumuluslinux/onie-installer-powerpc"
dhcp::cumulus_provision_url: "http://repo.%{domain}/cumuluslinux/provision.sh"

# Enable extra yum repo
profile::base::yumrepo::repo_hash:
  foreman:
    ensure: present
  foreman-plugins:
    ensure: present

# Enable gem installation
profile::base::common::manage_gems: true
profile::base::common::gems:
  'ipaddress': {}
