---
include:
  default:
    - profile::openstack::openrc
    - profile::logging::rsyslog::client
    - profile::webserver::apache
    - profile::application::builder

profile::base::common::packages:
  'python-openstackclient': {}
  'packer': {}
  'python34': {}
  'qemu-img': {}

profile::base::lvm::physical_volume:
  '/dev/vdb':
    ensure: present
    force:  true
profile::base::lvm::volume_group:
  'vg_images':
    physical_volumes:
      - /dev/vdb
profile::base::lvm::logical_volume:
  'lv_images':
    volume_group: 'vg_images'
    fs_type:      "xfs"
    mountpath:    "/opt"

profile::webserver::apache::vhosts:
  'builds':
    servername:     "builds.%{hiera('domain_mgmt')}"
    ip:             "%{::ipaddress_mgmt1}"
    port:           80
    docroot:        '/opt/images/public_builds'
    docroot_owner:  'iaas'

profile::openstack::openrc::filename:         '/home/imagebuilder/openrc'
profile::openstack::openrc::username:         'imagebuilder'
profile::openstack::openrc::project_name:     'imagebuilder'
profile::openstack::openrc::password:         "%{hiera('imagebuilder_password')}"

profile::application::builder::flavor:        'img.zerodisk'
profile::application::builder::template_dir:  '/etc/imagebuilder'
profile::application::builder::download_dir:  '/opt/images/public_builds'
profile::application::builder::rc_file:       '/home/imagebuilder/openrc'
profile::application::builder::images:
  'centos6':
    'image_name':       'IMAGEBUILDER CentOS 6'
    'url':              'http://cloud.centos.org/centos/6/images/'
    'latest':           'CentOS-6-x86_64-GenericCloud.qcow2'
    'checksum_file':    'sha256sum.txt'
    'checksum':         'sha256'
    'min_ram':          1024
    'min_disk':         8
    'username':         'centos'
  'centos7':
    'image_name':       'IMAGEBUILDER CentOS 7'
    'url':              'http://cloud.centos.org/centos/7/images/'
    'latest':           'CentOS-7-x86_64-GenericCloud.qcow2'
    'checksum_file':    'sha256sum.txt'
    'checksum':         'sha256'
    'min_ram':          768
    'min_disk':         8
    'username':         'centos'
  'fedora_25':
    'image_name':       'IMAGEBUILDER Fedora 25'
    'url':              'https://www.mirrorservice.org/sites/dl.fedoraproject.org/pub/fedora/linux/releases/25/CloudImages/x86_64/images/'
    'latest':           'Fedora-Cloud-Base-25-1.3.x86_64.qcow2'
    'checksum_file':    'Fedora-CloudImages-25-1.3-x86_64-CHECKSUM'
    'checksum':         'sha256'
    'min_ram':          768
    'min_disk':         3
    'username':         'fedora'
  'ubuntu_1604':
    'image_name':       'IMAGEBUILDER Ubuntu server 16.04'
    'url':              'https://cloud-images.ubuntu.com/xenial/current/'
    'latest':           'xenial-server-cloudimg-amd64-disk1.img'
    'checksum_file':    'SHA256SUMS'
    'checksum':         'sha256'
    'min_ram':          768
    'min_disk':         3
    'username':         'ubuntu'
  'debian8':
    'image_name':       'IMAGEBUILDER Debian Jessie 8'
    'url':              'http://cdimage.debian.org/cdimage/openstack/current-8/'
    'latest':           'debian-8-20170521-openstack-amd64.qcow2'
    'checksum_file':    'SHA256SUMS'
    'checksum':         'sha256'
    'min_ram':          768
    'min_disk':         3
    'username':         'debian'

# Enable extra yum repo
profile::base::yumrepo::repo_hash:
  rdo-release:
    ensure: present
