---
include:
  default:
    - profile::openstack::openrc
    - profile::webserver::apache
    - profile::application::builder

profile::base::common::packages:
  'python-openstackclient': {}
  'imagebuilder': {}
  'packer': {}

# Enable extra yum repo
profile::base::yumrepo::repo_hash:
  rdo-release:
    ensure: present

profile::webserver::apache::vhosts:
  'builds':
    servername:     "builds.%{hiera('domain_mgmt')}"
    port:           80
    docroot:        '/opt/images/public_builds'
    docroot_owner:  'iaas'

profile::openstack::openrc::filename: '/home/imagebuilder/openrc'
profile::openstack::openrc::username: 'imagebuilder'
profile::openstack::openrc::project_name: 'imagebuilder'

profile::application::builder::template_dir: '/opt/imagebuilder'
profile::application::builder::download_dir: '/opt/images/public_builds'
profile::application::builder::rc_file: '/home/imagebuilder/openrc'
profile::application::builder::images:
  'cirros':
    'image_name':       'CirrOS debug image'
    'url':              'http://download.cirros-cloud.net/0.3.4/'
    'latest':           'cirros-0.3.4-x86_64-disk.img'
    'checksum_file':    'MD5SUMS'
    'checksum':         'md5'
    'min_ram':          256
    'min_disk':         1
    'username':         'cirros'
  'centos6':
    'image_name':       'GOLD CentOS 6'
    'url':              'http://cloud.centos.org/centos/6/images/'
    'latest':           'CentOS-6-x86_64-GenericCloud.qcow2'
    'checksum_file':    'sha256sum.txt'
    'checksum':         'sha256'
    'min_ram':          1024
    'min_disk':         8
    'username':         'centos'
  'centos':
    'image_name':       'GOLD CentOS 7'
    'url':              'http://cloud.centos.org/centos/7/images/'
    'latest':           'CentOS-7-x86_64-GenericCloud.qcow2'
    'checksum_file':    'sha256sum.txt'
    'checksum':         'sha256'
    'min_ram':          768
    'min_disk':         8
    'username':         'centos'
  'fedora_25':
    'image_name':       'GOLD Fedora 25'
    'url':              'https://www.mirrorservice.org/sites/dl.fedoraproject.org/pub/fedora/linux/releases/25/CloudImages/x86_64/images/'
    'latest':           'Fedora-Cloud-Base-25-1.3.x86_64.qcow2'
    'checksum_file':    'Fedora-CloudImages-25-1.3-x86_64-CHECKSUM'
    'checksum':         'sha256'
    'min_ram':          768
    'min_disk':         8
    'username':         'fedora'
  'ubuntu':
    'image_name':       'GOLD Ubuntu server 16.04'
    'url':              'https://cloud-images.ubuntu.com/xenial/current/xenial-server-cloudimg-amd64-disk1.img'
    'latest':           'xenial-server-cloudimg-amd64-disk1.img'
    'checksum_file':    'SHA256SUMS'
    'checksum':         'sha256'
    'min_ram':          768
    'min_disk':         8
    'username':         'ubuntu'
  'debian':
    'image_name':       'GOLD Debian Jessie 8'
    'url':              'http://cdimage.debian.org/cdimage/openstack/current-8/'
    'latest':           'debian-8-openstack-amd64.qcow2'
    'checksum_file':    'SHA256SUMS'
    'checksum':         'sha256'
    'min_ram':          768
    'min_disk':         8
    'username':         'debian'
