---
include:
  default:
    - profile::openstack::openrc
    - profile::logging::rsyslog::client
    - profile::webserver::apache
    - profile::application::builder

profile::base::common::packages:
  'python-openstackclient': {}
  'packer': {}
  'python3': {}
  'qemu-img': {}
  'bash-completion': {}
  'bash-completion-extras': {}
  'jq': {}

named_interfaces::config:
  mgmt:
    - eth0

profile::base::lvm::physical_volume:
  '/dev/vdb':
    ensure: present
    force:  true
profile::base::lvm::volume_group:
  'vg_images':
    physical_volumes:
      - /dev/vdb
profile::base::lvm::logical_volume:
  'lv_images':
    volume_group: 'vg_images'
    fs_type:      "xfs"
    mountpath:    "/opt/images"

profile::webserver::apache::vhosts:
  'builds':
    servername:     "builder.%{hiera('domain_mgmt')}"
    ip:             "%{::ipaddress_mgmt1}"
    port:           80
    docroot:        '/opt/images/public_builds'
    docroot_owner:  'iaas'

profile::openstack::openrc::filename:         '/home/imagebuilder/openrc'
profile::openstack::openrc::username:         'imagebuilder'
profile::openstack::openrc::project_name:     'imagebuilder'
profile::openstack::openrc::password:         "%{hiera('imagebuilder_password')}"
profile::openstack::openrc::interface:        'public'


profile::application::builder::package_url:   'https://download.iaas.uio.no/uh-iaas/yumrepo/imagebuilder-1.0-6.el7.x86_64.rpm'
profile::application::builder::ipv6:          true
profile::application::builder::flavor:        'img.zerodisk'
profile::application::builder::template_dir:  '/etc/imagebuilder'
profile::application::builder::download_dir:  '/opt/images/public_builds'
profile::application::builder::rc_file:       '/home/imagebuilder/openrc'
profile::application::builder::images:
  'centos7':
    'image_name':       'IMAGEBUILDER CentOS 7'
    'url':              'http://cloud.centos.org/centos/7/images/'
    'latest':           'CentOS-7-x86_64-GenericCloud.qcow2'
    'checksum_file':    'sha256sum.txt'
    'checksum':         'sha256'
    'min_ram':          768
    'min_disk':         8
    'username':         'centos'
  'centos8':
    'image_name':       'IMAGEBUILDER CentOS 8'
    'url':              'http://cloud.centos.org/centos/8/x86_64/images/'
    'latest':           'CentOS-8-GenericCloud-8.2.2004-20200611.2.x86_64.qcow2'
    'checksum_file':    'CHECKSUM'
    'checksum':         'sha256'
    'min_ram':          768
    'min_disk':         8
    'username':         'centos'
  'fedora_32':
    'image_name':       'IMAGEBUILDER Fedora 32'
    'url':              'https://www.mirrorservice.org/sites/dl.fedoraproject.org/pub/fedora/linux/releases/32/Cloud/x86_64/images/'
    'latest':           'Fedora-Cloud-Base-32-1.6.x86_64.qcow2'
    'checksum_file':    'Fedora-Cloud-32-1.6-x86_64-CHECKSUM'
    'checksum':         'sha256'
    'min_ram':          768
    'min_disk':         3
    'username':         'fedora'
  'ubuntu_1804':
    'image_name':       'IMAGEBUILDER Ubuntu 18.04 LTS'
    'url':              'https://cloud-images.ubuntu.com/bionic/current/'
    'latest':           'bionic-server-cloudimg-amd64.img'
    'checksum_file':    'SHA256SUMS'
    'checksum':         'sha256'
    'min_ram':          768
    'min_disk':         3
    'username':         'ubuntu'
  'ubuntu_2004':
    'image_name':       'IMAGEBUILDER Ubuntu 20.04'
    'url':              'https://cloud-images.ubuntu.com/focal/current/'
    'latest':           'focal-server-cloudimg-amd64.img'
    'checksum_file':    'SHA256SUMS'
    'checksum':         'sha256'
    'min_ram':          768
    'min_disk':         3
    'username':         'ubuntu'
  'debian9':
    'image_name':       'IMAGEBUILDER Debian 9'
    'url':              'http://cdimage.debian.org/cdimage/openstack/current-9/'
    'latest':           'debian-9-openstack-amd64.qcow2'
    'checksum_file':    'SHA256SUMS'
    'checksum':         'sha256'
    'min_ram':          768
    'min_disk':         3
    'username':         'debian'
  'debian10':
    'image_name':       'IMAGEBUILDER Debian 10'
    'url':              'http://cdimage.debian.org/cdimage/openstack/current-10/'
    'latest':           'debian-10-openstack-amd64.qcow2'
    'checksum_file':    'SHA256SUMS'
    'checksum':         'sha256'
    'min_ram':          768
    'min_disk':         3
    'username':         'debian'
  'uio_rhel7':
    'image_name':       'IMAGEBUILDER UIO RHEL 7'
    'url':              'http://download.iaas.uio.no/uh-iaas/nonfree/'
    'latest':           'rhel-server-7.9-x86_64-kvm.qcow2'
    'checksum_file':    'rhel-server-7.9-x86_64-kvm.sha256sum'
    'checksum':         'sha256'
    'min_ram':          1024
    'min_disk':         8
    'username':         'cloud-user'
  'uio_rhel8':
    'image_name':       'IMAGEBUILDER UIO RHEL 8'
    'url':              'http://download.iaas.uio.no/uh-iaas/nonfree/'
    'latest':           'rhel-8.3-x86_64-kvm.qcow2'
    'checksum_file':    'rhel-8.3-x86_64-kvm.sha256sum'
    'checksum':         'sha256'
    'min_ram':          1024
    'min_disk':         8
    'username':         'cloud-user'


# Sensu
profile::monitoring::sensu::agent::plugin_gems:
  sensu-plugins-himlar:
    ensure:       '0.6.0'
    provider:     'sensuclassic_gem'
    source:       'http://download.iaas.uio.no/uh-iaas/gem'

# metadata imagebuild check
profile::monitoring::sensu::agent::expanded_checks:
  - 'centos7'
  - 'centos8'
  - 'fedora_32'
  - 'ubuntu_1804'
  - 'ubuntu_2004'
  - 'debian9'
  - 'debian10'
  - 'uio_rhel7'

profile::monitoring::sensu::agent::expanded_defaults:
    command: "check-imagebuild.rb -d "
    interval:     600
    subscribers:  ['checks']

# Enable extra yum repo
profile::base::yumrepo::repo_hash:
  rdo-release:
    ensure: present
  epel:
    ensure: present
    includepkgs: 'bash-completion-extras htop inotify-tools python-dogpile-core python-linecache2 python-repoze-lru python-unicodecsv python-warlock python2-asn1crypto python2-funcsigs python2-iso8601 python2-jmespath python2-mimeparse python2-msgpack python2-pbr python2-pysocks python2-rfc3986 python2-wcwidth python34 python34-libs'

# Turn on agant and add common sensu plugins
profile::monitoring::sensu::agent::enable_agent: true
# profile::monitoring::sensu::agent::plugins:
#   sensu-plugins-logs:
#     type:         package

# # metadata check
# profile::monitoring::sensu::agent::checks:
#   'check-log':
#     command:      "sudo /opt/sensu/embedded/bin/check-log.rb -f /var/log/cron -w 1 -c 1 -q 'imagebuilder: Failed building' -r"
#     interval:     60
#     auto_resolve: false
#     handlers:     'slack'
#     subscribers:  ['checks']

sudo::configs:
  sensu_tty:
    priority:   15
    content:    'Defaults:sensu !requiretty'
  sensu:
    priority:   20
    content:    'sensu ALL = (root) NOPASSWD: /opt/sensu/embedded/bin/check-log.rb'

profile::monitoring::sensu::agent::checks:
  'check-log':
    command:      cat /var/log/imagebuilder/*-report.jsonl | jq -r 'select(.result) | .result'
    interval:     60
    auto_resolve: false
    subscribers:  ['checks']
