---
include:
  default:
    - profile::storage::cephmon
    - profile::storage::cephmon_firewall
  bootstrap:
    - profile::storage::cephmon_firewall

profile::storage::cephmon_firewall::manage_firewall:  true

profile::base::common::packages:
  'redhat-lsb-core': {}
  'bash-completion': {}
  'bash-completion-extras': {}
  'jq': {}

accounts::users:
  'cinder':
    ensure: present
  'glance':
    ensure: present

accounts::usergroups:
  'cinder':
    - 'cinder'
  'glance':
    - 'glance'

accounts::accounts:
  'cinder':
    ensure: present
  'glance':
    ensure: present

# Sensu
profile::monitoring::sensu::agent::plugins:
  sensu-plugins-ceph:
    type:         package
    pkg_version:  '0.0.5'

# Enable extra yum repo
profile::base::yumrepo::repo_hash:
  ceph-%{hiera('ceph_version')}:
    ensure: present
