---
include:
  default:
    - profile::openstack::compute::migration
    - profile::openstack::compute::hypervisor
    - profile::openstack::volume
    - profile::openstack::network
    - profile::logging::rsyslog::client
    - profile::openstack::openrc
  kickstart:
    - profile::base::lvm
    - profile::virtualization::nested
    - profile::network::yum_proxy
    - profile::monitoring::sensu::agent
  bootstrap:
    - profile::base::lvm
    - profile::network::yum_proxy

# Because of this we cannot use syslog on master:
# https://bugs.launchpad.net/kolla/liberty/+bug/1516306
neutron::use_syslog:    true
neutron::log_facility:  'LOG_LOCAL5'

profile::base::network::manage_httpproxy: true
profile::network::yum_proxy::yum_proxy:   "http://%{hiera('mgmt__address__proxy')}:8888"

# Source proxy for internet access during puppetrun
puppet::cron_cmd: "if [ -e /root/proxy.sh ] ; then source /root/proxy.sh ; fi ; \
  /usr/bin/env puppet agent --config %{puppet::dir}/puppet.conf --onetime --no-daemonize"

profile::openstack::compute::migration::enable_nova_account: true

# Enable intance migration via ssh
profile::firewall::pre::ssh_settings:
  source: "0.0.0.0/0" #FIXME (limit source)

openstack_extras::repo::redhat::redhat::manage_rdo: false
profile::base::common::manage_lvm: true

profile::openstack::openrc::password:     "%{hiera('nova_api_password')}"
profile::openstack::openrc::username:     'nova'
profile::openstack::openrc::project_name: 'services'

dnsmasq::package_ensure: '2.72_calico1.0.0-1.el7'

profile::openstack::network::plugin: calico

profile::base::common::packages:
  'posix-spawn': {}
  'networking-calico': {}
  'python-openstackclient': {}
  'gcc-c++': {}

# Sensu (needs gcc-c++)
profile::monitoring::sensu::agent::plugins:
  sensu-plugins-http:
    type:         package
    pkg_version:  '1.0.0'

# metadata api check
profile::monitoring::sensu::agent::checks:
  'metadata-api':
    command:      "check-http.rb -u http://127.0.0.1:8775"
    interval:     30
    subscribers:  ['checks']

profile::openstack::compute::hypervisor::fix_snapshot_loc: true # FIXME - Should probably be removed for newton release

calico::compute: true
etcd::mode: 'proxy'

calico::compute::bird_template: 'profile/bird/bird.conf.erb'

named_interfaces::config:
  mgmt:
    - em3
  transport: #FIXME
    - team1
  trp:
    - team1
  service: #FIXME
    - team1


sudo::purge: false

accounts::users:
  'cinder':
    ensure: present
  'glance':
    ensure: present

accounts::usergroups:
  'cinder':
    - 'cinder'
  'glance':
    - 'glance'

accounts::accounts:
  'cinder':
    ensure: present
  'glance':
    ensure: present

profile::base::lvm::physical_volume:
  '/dev/sda3':
    ensure: present
    force:  true
profile::base::lvm::volume_group:
  'vg_ext':
    physical_volumes:
      - /dev/sda3
profile::base::lvm::logical_volume:
  'lv_instances':
    volume_group: 'vg_ext'
    fs_type:      "xfs"
    mountpath:    "/var/lib/nova/instances"

# Enable extra yum repo
profile::base::yumrepo::repo_hash:
  rdo-release:
    ensure: present
  calico:
    ensure: present
    exclude: 'calico-dhcp-agent' #FIXME
  ceph-jewel:
    ensure: present
