---
include:
  default:
    - profile::openstack::compute::consoleproxy
    - profile::logging::rsyslog::client

profile::base::common::packages:
  'bash-completion': {}
  'bash-completion-extras': {}
  'jq': {}

profile::base::network::manage_dummy:                       true
profile::openstack::compute::consoleproxy::manage_firewall: true
profile::openstack::compute::consoleproxy::spice:           true

nova::config::nova_config:
    DEFAULT/ssl_only:
      value: true
    DEFAULT/ca_file:
      value: "/etc/pki/tls/certs/cachain.pem"
    DEFAULT/cert:
      value: "/etc/pki/tls/certs/console.%{hiera('domain_public')}.cert.pem"
    DEFAULT/key:
      value: "/etc/pki/tls/private/console.%{hiera('domain_public')}.key.pem"

# Enable extra yum repo
profile::base::yumrepo::repo_hash:
  rdo-release:
    ensure: present
