---
include:
  default:
    - profile::openstack::database::sql
    - profile::monitoring::sensu::mysql
    - profile::logging::logrotate

# These should be set to valid options per location
db_ssl_key:       '/etc/mysql/server-key.pem'
db_ssl_cert:      '/etc/mysql/server-cert.pem'
db_ssl_ca:        '/etc/mysql/cacert.pem'

# Galera options
profile::base::common::packages:
  'bzip2':                  {}
  'rsync':                  {}
  'socat':                  {}
  'MariaDB-backup':         {}
  'bash-completion':        {}
  'bash-completion-extras': {}
  'jq': {}

profile::database::galera::wsrep_sst_secure_rsync:
  ca:   "%{hiera('db_ssl_ca')}"
  key:  "%{hiera('db_ssl_key')}"
  cert: "%{hiera('db_ssl_cert')}"

# Default values are no cluster and no tls
# ONLY TURN ON CLUSTER ON INDIVIDUAL NODES!
wsrep_provider_options: "base_host=%{::ipaddress_trp1};pc.recovery=1;"
wsrep_sst_method:       'rsync'
wsrep_cluster_address:  'gcomm://'
wsrep_node_address:     "%{::ipaddress_trp1}"

# Sensu
profile::monitoring::sensu::mysql::password:  "%{hiera('sensu_mysql_password')}"
profile::monitoring::sensu::mysql::manage_packages: true

profile::monitoring::sensu::agent::plugins:
  sensu-plugins-mysql:
    type:         package
    pkg_version:  '2.3.0'
  sensu-plugins-percona:
    type:         package
    pkg_version:  '1.1.0'

profile::monitoring::sensu::agent::checks:
  'metrics-mysql-graphite':
    type:         'metric'
    command:      'metrics-mysql-graphite.rb --scheme mysql.%{::hostname} -h localhost -S /var/lib/mysql/mysql.sock --ini /etc/sensu/conf.d/mysql.ini'
    interval:     60
    subscribers:  ['metrics']
    handlers:     ['graphite_tcp']
  'check-mysql-alive':
    command:      'check-mysql-alive.rb -h localhost -s /var/lib/mysql/mysql.sock --ini /etc/sensu/conf.d/mysql.ini'
    interval:     60
    subscribers:  ['checks']

# Logrotate
profile::logging::logrotate::manage_logrotate:   true
logrotate::rules:
  mysql:
    path:           '/var/log/mysqld.log'
    rotate:         14
    postrotate: >-
      if test -x /usr/bin/mysqladmin && /usr/bin/mysqladmin ping &>/dev/null; then
            /usr/bin/mysqladmin --local flush-error-log flush-engine-log flush-general-log flush-slow-log
          fi
    sharedscripts:  true
    copytruncate:   true
    missingok:      true
    rotate_every:   daily
    compress:       true
  syslog:
    path:           ['/var/log/cron', '/var/log/maillog', '/var/log/messages', '/var/log/secure', '/var/log/spooler']
    rotate:         10
    rotate_every:   daily
    postrotate:     '/bin/kill -HUP `cat /var/run/syslogd.pid 2> /dev/null` 2> /dev/null || true'
    dateext:        true
    sharedscripts:  true
    missingok:      true
    compress:       true

profile::openstack::database::sql::extra_databases:
  horizon: # Session database
    password:       "%{hiera('horizon_db_password')}"
    user:           'horizon'
    host:           "%{hiera('netcfg_trp_netpart')}.51"

# Enable extra yum repo
profile::base::yumrepo::repo_hash:
  mariadb:
    ensure: present


# for backup

# ... script creation
profile::database::mariadb::backupuser:       'root'
profile::database::mariadb::backuppassword:   "%{hiera('mysql::server::root_password')}"
profile::database::mariadb::postscript:       "date >  %{hiera('profile::database::mariadb::backuptopdir')}/$(hostname)-backupflag"
profile::database::mariadb::file_per_database: true
profile::database::mariadb::maxallowedpacket:  4096
