---
include:
  default:
    - profile::openstack::designate
    - profile::openstack::cache
    - profile::logging::rsyslog::client
    - profile::openstack::openrc
    - profile::dns::rndc_key

profile::dns::rndc_key::create_admin_key:    false
profile::dns::rndc_key::create_mdns_key:     true
profile::dns::rndc_key::host_is_bind_server: false

profile::openstack::openrc::password:     "%{hiera('designate_api_password')}"
profile::openstack::openrc::username:     'designate'
profile::openstack::openrc::project_name: 'services'

profile::openstack::designate::mdns_transport_addr:   "%{hiera('service__address__mdns')}"
profile::openstack::designate::ns_transport_addr:     "%{hiera('service__address__ns')}"
profile::openstack::designate::ns_public_addr:        "%{hiera('public__address__ns')}"
profile::openstack::designate::ns_public_name:        "%{hiera('public__name__ns')}"

# Add iptables rules
profile::openstack::designate::manage_firewall: true

# 1. We want /usr/bin/openstack (not sure if it's strictly needed)
# 2. designate-manage requires python2-oslo-reports and python2-suds
# 3. pool-manager requires python-tooz
# 4. we use memcache as pool manager cache
profile::base::common::packages:
  'python-openstackclient': {}
  'python2-oslo-reports': {}
  'python2-suds': {}
  'python-tooz': {}
  'openstack-utils': {}
  'openstack-selinux': {}
  'patch': {}

# Don't purge sudo stuff
sudo::purge: false

# Override repo "rdo-release"
openstack_version: 'pike'

# Enable extra yum repo
profile::base::yumrepo::repo_hash:
  rdo-release:
    ensure: present
