---
include:
  default:
    - profile::openstack::congress
    - profile::openstack::cache
    - profile::logging::rsyslog::client
    - profile::openstack::openrc

# Username and password for the congress service
profile::openstack::openrc::password:     "%{hiera('congress_api_password')}"
profile::openstack::openrc::username:     'congress'
profile::openstack::openrc::project_name: 'services'

# Set SELinux enforcing
profile::base::selinux::manage_selinux: true

# Add iptables rules
profile::openstack::congress::manage_firewall: true

# Some extra packages we want installed
profile::base::common::packages:
  'python2-openstackclient': {}
  'openstack-utils': {}
  'openstack-selinux': {}
  'patch': {}

# Don't purge sudo stuff
sudo::purge: false

# Override repo "rdo-release"
#openstack_version: 'rocky'

# Enable extra yum repo
profile::base::yumrepo::repo_hash:
  rdo-release:
    ensure: present

# Make sure that memcached doesn't too much memory
memcached::max_memory: '20%'