---
include:
  default:
    - profile::openstack::identity
    - profile::openstack::resource::imagebuilder
    - profile::openstack::resource::dataporten
    - profile::openstack::resource::users
    - profile::openstack::openrc
    - profile::application::himlarcli
    - profile::logging::rsyslog::client

profile::base::common::packages:
  'bash-completion': {}
  'bash-completion-extras': {}
  'jq': {}
  'sharutils': {}
  'MariaDB-client': {}

profile::base::selinux::manage_selinux:                   false
profile::openstack::identity::disable_admin_token_auth:   true
profile::openstack::identity::manage_openidc:             true
profile::openstack::identity::trusted_dashboard:          "https://%{hiera('public__address__dashboard')}/dashboard/auth/websso/"
profile::openstack::identity::roles_extra:
  - user
  - superuser
profile::openstack::identity::keystone_config:
  'resource/project_name_url_safe':
    value:  'new'
  'resource/domain_name_url_safe':
    value:  'new'
  'cors/allowed_origin': # allow gnocchi access on monitor
    value:  "http://%{hiera('mgmt__address__monitor')}:8080"

# Key rotation and syncronization
profile::openstack::identity::cron_master:
  'fernet':
    hour:     '*'
    minute:   '20'
    command:  '/usr/local/sbin/token_dist.sh fernet >/dev/null'
  'credentials':
    hour:     '*'
    minute:   '30'
    command:  '/usr/local/sbin/token_dist.sh credentials >/dev/null'
  'credential_rotate':
    hour:     '3'
    minute:   '25'
    command:  'keystone-manage credential_rotate'
    user:     'keystone'

profile::openstack::identity::cron_slave:
  'fernet':
    hour:     '*'
    minute:   '25'
    command:  '/usr/local/sbin/token_dist.sh fernet >/dev/null'
  'credentials':
    hour:     '*'
    minute:   '35'
    command:  '/usr/local/sbin/token_dist.sh credentials >/dev/null'

profile::openstack::identity::token_rotation_sync:          true
profile::openstack::identity::fernet_key_repo:              "%{hiera('keystone::fernet_key_repository')}"
profile::openstack::identity::credential_key_repo:          "%{hiera('keystone::credential_key_repository')}"
profile::openstack::identity::db_host:                      "db01.%{hiera('domain_trp')}"
profile::openstack::identity::dbpw:                         "%{hiera('keystone::db::mysql::password')}"
profile::openstack::identity::gpg_receiver:                 "%{hiera('gpg_receiver')}"
profile::openstack::identity::fernet_active_keys:           "%{hiera('keystone::fernet_max_active_keys')}"
profile::openstack::identity::credential_active_keys:       "2"                                                 # no value for this in keystone module


profile::openstack::openrc::filename:                       '/root/keystonerc_admin'

profile::openstack::resource::imagebuilder::manage:         true
profile::openstack::resource::imagebuilder::password:       "%{hiera('imagebuilder_password')}"

profile::openstack::resource::dataporten::manage_dataporten: true
profile::openstack::resource::dataporten::domain:
  dataporten:
    ensure:       present
    description:  'Federated users from Dataporten'
    is_default:   false
profile::openstack::resource::dataporten::identity_provider:
  dataporten:
    enabled:      true
    remote_ids:   [ 'https://auth.dataporten.no' ]
    description:  'Federated user from Dataporten'

# Custom users
profile::openstack::resource::users::users:
  status:
    enabled:  true
    email:    'status@localhost'
    password: "%{hiera('status_metric_password')}"
  monitor:
    enabled:  true
    email:    'monitor@localhost'
    password: "%{hiera('monitor_metric_password')}"
profile::openstack::resource::users::user_roles:
  'status@services':
    roles:    'user'
  'monitor@services':
    roles:    'user'

# Enable extra yum repo
profile::base::yumrepo::repo_hash:
  rdo-release:
    ensure:   present
    exclude:  'mariadb*'
  mariadb:
    ensure:   present

profile::base::selinux::boolean:
  'httpd_can_network_connect':
    ensure: 'on'
    persistent: true
  'httpd_can_network_connect_db':
    ensure: 'on'
    persistent: true
  'httpd_use_openstack':
    ensure: 'on'
    persistent: true
