---
include:
  default:
    - profile::openstack::identity
    - profile::openstack::resource::imagebuilder
    - profile::openstack::resource::dataporten
    - profile::openstack::openrc
    - profile::application::himlarcli
    - profile::logging::rsyslog::client

profile::base::common::packages:
  'bash-completion': {}
  'bash-completion-extras': {}
  'jq': {}

#profile::openstack::identity::manage_token_rotate:        true
profile::openstack::identity::disable_admin_token_auth:   true
profile::openstack::identity::manage_openidc:             true
profile::openstack::identity::trusted_dashboard:          "https://%{hiera('public__address__dashboard')}/dashboard/auth/websso/"
profile::openstack::identity::roles_extra:
  - user
  - superuser
profile::openstack::identity::keystone_config:
  'resource/project_name_url_safe':
    value:  'new'
  'resource/domain_name_url_safe':
    value:  'new'

profile::openstack::openrc::filename:                       '/root/keystonerc_admin'

profile::openstack::resource::imagebuilder::manage:         true
profile::openstack::resource::imagebuilder::password:       "%{hiera('imagebuilder_password')}"

profile::openstack::resource::dataporten::manage_dataporten: true
profile::openstack::resource::dataporten::domain:
  dataporten:
    ensure:       present
    description:  'Federated users from Dataporten'
    is_default:   false
profile::openstack::resource::dataporten::identity_provider:
  dataporten:
    enabled:      true
    remote_ids:   [ 'https://auth.dataporten.no' ]
    description:  'Federated user from Dataporten'

# Enable extra yum repo
profile::base::yumrepo::repo_hash:
  rdo-release:
    ensure: present
