---
include:
  default:
    - profile::openstack::image
    - profile::openstack::openrc
    - profile::logging::rsyslog::client

profile::openstack::image::registry_enabled:  true

profile::openstack::openrc::password:     "%{hiera('glance_api_password')}"
profile::openstack::openrc::username:     'glance'
profile::openstack::openrc::project_name: 'services'

accounts::users:
  'cinder':
    ensure: present

accounts::usergroups:
  'cinder':
    - 'cinder'

accounts::accounts:
  'cinder':
    ensure: present

# Enable extra yum repo
profile::base::yumrepo::repo_hash:
  rdo-release:
    ensure: present
  ceph-jewel:
    ensure: present
