---
include:
  default:
    - profile::openstack::image
    - profile::openstack::openrc
    - profile::logging::rsyslog::client

profile::base::common::packages:
  'bash-completion': {}
  'bash-completion-extras': {}
  'jq': {}

profile::openstack::image::registry_enabled:  true
profile::openstack::image::manage_policy:     true

profile::openstack::openrc::password:     "%{hiera('glance_api_password')}"
profile::openstack::openrc::username:     'glance'
profile::openstack::openrc::project_name: 'services'

# Enable extra yum repo
profile::base::yumrepo::repo_hash:
  rdo-release:
    ensure: present
  ceph-%{hiera('ceph_version')}:
    ensure: present

# Image nodes need only glance key
ceph::profile::params::client_keys:
  'client_glance':
    secret: "%{hiera('client_glance::secret')}"
    mode: '0600'
    user: 'glance'
    group: 'glance'
    cap_mon: 'allow r'
    cap_osd: 'allow class-read object_prefix rbd_children, allow rwx pool=images'
