---
include:
  default:
    - profile::logging::rsyslog::server
    - profile::logging::logstash
    - profile::logging::elasticsearch
    - profile::logging::kibana
    - profile::logging::logrotate

rsyslog::perm_dir:    '0755'

profile::logging::logrotate::manage_logrotate:   true
profile::logging::elasticsearch::manage_curator: true
profile::logging::elasticsearch::instances:
  'openstack':
    datadir:  '/opt/els/openstack'
    config:
      'cluster.name':             "logger"
      'index.number_of_replicas': '0'
      'index.number_of_shards':   '1'
      'network.host':             "127.0.0.1"
      'node.name':                "%{::hostname}"

profile::base::common::packages:
  'java-1.8.0-openjdk':     {}
  'elasticsearch-curator':  {}
  'bash-completion': {}
  'bash-completion-extras': {}
  'jq': {}

profile::base::lvm::physical_volume:
  '/dev/vdb':
    ensure: present
    force:  true
profile::base::lvm::volume_group:
  'vg_log':
    physical_volumes:
      - /dev/vdb
profile::base::lvm::logical_volume:
  'lv_log':
    volume_group: 'vg_log'
    fs_type:      "xfs"
    mountpath:    "/opt/log"
    size:         '10G'
  'lv_els':
    volume_group: 'vg_log'
    fs_type:      "xfs"
    mountpath:    "/opt/els"

logrotate::rules:
  openstack:
    path:           '/opt/log/*.log'
    rotate:         30
    postrotate:     '/bin/kill -HUP `cat /var/run/syslogd.pid 2> /dev/null` 2> /dev/null || true'
    sharedscripts:  true
    missingok:      true
    rotate_every:   daily
    compress:       true
  messages:
    path:           '/opt/log/*/messages'
    rotate:         30
    postrotate:     '/bin/kill -HUP `cat /var/run/syslogd.pid 2> /dev/null` 2> /dev/null || true'
    sharedscripts:  true
    missingok:      true
    rotate_every:   daily
    compress:       true

# Enable extra yum repo
profile::base::yumrepo::repo_hash:
  logstash:
    ensure: present
  elasticsearch:
    ensure: present
  curator:
    ensure: present
