---
include:
  default:
    - profile::logging::rsyslog::client
    - profile::openstack::openrc

profile::openstack::openrc::password:     "%{hiera('designate_api_password')}"
profile::openstack::openrc::username:     'designate'
profile::openstack::openrc::project_name: 'services'

profile::openstack::designate::dns_master:  "%{hiera('service__address__dns_master')}"
profile::openstack::designate::dns_slave01: "%{hiera('service__address__dns_slave01')}"
profile::openstack::designate::dns_slave02: "%{hiera('service__address__dns_slave02')}"
profile::openstack::designate::mdns_server: "%{hiera('service__address__designate_api')}"
