---
include:
  default:
    - profile::logging::rsyslog::client
    - profile::openstack::openrc

profile::openstack::openrc::password:     "%{hiera('designate_api_password')}"
profile::openstack::openrc::username:     'designate'
profile::openstack::openrc::project_name: 'services'

profile::openstack::designate::mdns_transport_addr: "%{hiera('service__address__mdns')}"
profile::openstack::designate::ns1_transport_addr:  "%{hiera('service__address__ns_01')}"
profile::openstack::designate::ns2_transport_addr:  "%{hiera('service__address__ns_02')}"
profile::openstack::designate::ns1_public_addr:     "%{hiera('public__address__ns_01')}"
profile::openstack::designate::ns2_public_addr:     "%{hiera('public__address__ns_02')}"
