---
include:
  default:
    - profile::network::nat

named_interfaces::config:
  mgmt:
    - eth0
  trp:
    - eth1
  public:
    - dummy0

bsd::network::v4forwarding: false

profile::base::network::net_ifnames:             true
profile::base::common::manage_keyboard:          true
profile::base::common::manage_yumrepo:           true
profile::base::common::manage_packages:          true
profile::monitoring::sensu::agent::enable_agent: true

profile::base::network::manage_dummy:            true

profile::network::nat::enable_bird:              true
profile::network::nat::manage_bird_firewall:     true

profile::network::nat::enable_snat:              true
profile::network::nat::outiface:                 "%{::interface_trp1}"
profile::network::nat::source:                   "!%{::ipaddress_trp1}"
