---
include:
  default:
    - profile::openstack::novactrl
    - profile::logging::rsyslog::client
    - profile::openstack::openrc
    - profile::openstack::resource::host_aggregate

profile::openstack::compute::api::manage_firewall:  true
profile::openstack::novactrl::enable_api:           true
profile::openstack::novactrl::enable_conductor:     true
profile::openstack::novactrl::enable_scheduler:     true
profile::openstack::novactrl::enable_consoleauth:   true
profile::openstack::novactrl::manage_quotas:        true
profile::openstack::novactrl::manage_az:            true

profile::openstack::openrc::password:     "%{hiera('nova_api_password')}"
profile::openstack::openrc::username:     'nova'
profile::openstack::openrc::project_name: 'services'

profile::openstack::compute::api::firewall_extras:
  source: "%{::network_trp1}/%{::netmask_trp1}"

profile::base::common::packages:
  'python-openstackclient': {}
  'bash-completion': {}
  'bash-completion-extras': {}
  'jq': {}

# Enable extra yum repo
profile::base::yumrepo::repo_hash:
  rdo-release:
    ensure: present
