---
include:
  default:
    - profile::openstack::novactrl
    - profile::logging::rsyslog::client
    - profile::openstack::openrc
    - profile::openstack::resource::host_aggregate
    - profile::openstack::cache
    - profile::webserver::apache::status

profile::base::selinux::manage_selinux:             true
profile::openstack::novactrl::manage_firewall:      true
profile::openstack::novactrl::enable_api:           true
profile::openstack::novactrl::enable_conductor:     true
profile::openstack::novactrl::enable_scheduler:     true
profile::openstack::novactrl::manage_az:            true
profile::openstack::novactrl::manage_cells:         true

profile::openstack::openrc::password:     "%{hiera('nova_api_password')}"
profile::openstack::openrc::username:     'nova'
profile::openstack::openrc::project_name: 'services'

profile::openstack::novactrl::firewall_extras:
  source: "%{::network_trp1}/%{::netmask_trp1}"

profile::base::common::packages:
  'bash-completion': {}
  'bash-completion-extras': {}
  'jq': {}
  'openstack-selinux': {}
  'python-memcached': {}

# Sensu
profile::webserver::apache::status::manage_status: true
profile::monitoring::sensu::agent::plugins:
  sensu-plugins-apache:
    type:         package
    pkg_version:  '3.0.0'

profile::monitoring::sensu::agent::checks:
  'metrics-httpd-overview':
    type:         'metric'
    command:      "metrics-apache-graphite.rb --scheme httpd.%{::hostname} -h 127.0.0.1"
    interval:     60
    subscribers:  ['metrics']
    handlers:     ['graphite_tcp']

# Enable extra yum repo
profile::base::yumrepo::repo_hash:
  rdo-release:
    ensure: present
  epel: # should be absent when using RDO, but whitelist can also work
    ensure:   present
    includepkgs: 'htop bash-completion-extras'

memcached::max_memory: '20%'

openstack_version:     'rocky'
