---
include:
  default:
    - profile::storage::cephosd
    - profile::storage::cephosd_firewall
    - profile::base::lvm
    - profile::storage::ceph::pool
  kickstart:
    - profile::base::lvm
  bootstrap:
    - profile::base::lvm
    - profile::storage::cephosd_firewall

# Override default from modules/ceph.yaml
ceph::profile::params::mon_host:              "%{::netpart_trp1}.89:6789"
ceph::profile::params::mon_initial_members:   '%{::location}-cephmon-object-01'
ceph::profile::params::cluster_network:       "%{::netpart_trp1}.0/%{cidr_trp1}"
ceph::profile::params::public_network:        "%{::netpart_trp1}.0/%{cidr_trp1}"
ceph::profile::params::osd_journal_size:      '10240'
ceph::profile::params::client_keys:
  'client.admin':
    secret: "%{hiera('ceph_object_client_admin_key')}"
    mode: '0600'
    user: 'ceph'
    group: 'ceph'
    cap_mon: 'allow *'
    cap_osd: 'allow *'
    cap_mgr: 'allow *'
  'client.bootstrap-osd':
    secret: "%{hiera('ceph_object_client_bootstrap_osd_key')}"
    keyring_path: '/var/lib/ceph/bootstrap-osd/ceph.keyring'
    cap_mon: 'allow profile bootstrap-osd'

profile::base::manage_lvm:                           true

profile::base::common::packages:
  'redhat-lsb-core': {}
  'bash-completion': {}
  'bash-completion-extras': {}
  'jq': {}

profile::storage::cephosd_firewall::manage_firewall: true
profile::storage::cephosd::create_osds:              true

profile::storage::ceph::pool::pools:
  default.rgw.control:
    size:       3
    pg_num:     32
    pgp_num:    32
    tag:          'rgw'
    custom:
      crush_rule: 'ssd'
  default.rgw.meta:
    size:       3
    pg_num:     32
    pgp_num:    32
    tag:          'rgw'
    custom:
      crush_rule: 'ssd'
  default.rgw.log:
    size:       3
    pg_num:     32
    pgp_num:    32
    tag:          'rgw'
    custom:
      crush_rule: 'ssd'
  default.rgw.buckets.index:
    size:       3
    pg_num:     32
    pgp_num:    32
    tag:          'rgw'
    custom:
      crush_rule: 'ssd'
  default.rgw.buckets.log:
    size:       3
    pg_num:     32
    pgp_num:    32
    tag:          'rgw'
    custom:
      crush_rule: 'hdd'
  default.rgw.buckets.meta:
    size:         3
    pg_num:       32
    pgp_num:      32
    tag:          'rgw'
    custom:
      crush_rule: 'ssd'
  # default.rgw.buckets.cache: # used for tiering
  #   size:         3
  #   pg_num:       128
  #   pgp_num:      128
  #   custom:
  #     crush_rule: 'ssd'

profile::storage::ceph::pool::ec_pools:
  default.rgw.buckets.data:
    k_data:     3
    m_code:     2
    pg_num:     512
    tag:        'rgw'
    custom:
      min_size: '4' # this should always be k + 1 in production

# profile::storage::ceph::pool::tiers:
#   rgw-default-cache:
#     storage_pool:       'default.rgw.buckets.data'
#     cache_pool:         'default.rgw.buckets.cache'
#     custom: # these will be set on cache_pool
#       hit_set_type:     'bloom'
#       hit_set_count:    '12'
#       hit_set_period:   '7200' # 2 hour
#       target_max_bytes: '1073741824' # 1 GB

profile::storage::ceph::pool::crush_rules:
  'hdd':
    rule_device_type: "hdd"
  'ssd':
    rule_device_type: "ssd"

sudo::configs:
  sensu_tty:
    priority: 20
    content:  'Defaults:sensu !requiretty'
  sensu:
    priority: 25
    content:  'sensu ALL=(ALL) NOPASSWD: /opt/sensu/embedded/bin/check-ceph.rb'

check_ceph_argument:    ''

profile::monitoring::sensu::agent::checks:
  'check-ceph':
    command:      "/usr/bin/sudo /opt/sensu/embedded/bin/check-ceph.rb %{hiera('check_ceph_argument')}"
    interval:     60
    subscribers:  ['checks']

profile::monitoring::sensu::agent::plugin_gems:
  sensu-plugins-himlar:
    ensure:   '0.3.0'
    provider: 'sensu_gem'
    source:   'http://download.iaas.uio.no/uh-iaas/gem'

# Enable extra yum repo
profile::base::yumrepo::repo_hash:
  ceph-%{hiera('ceph_version')}:
    ensure: present
