---
include:
  default:
    - profile::monitoring::prometheus

profile::monitoring::prometheus::server: true

profile::monitoring::prometheus::server::manage_firewall: true
profile::monitoring::prometheus::server::package_name: 'prometheus2'

profile::base::yumrepo::repo_hash:
  epel:
    ensure: present
  prometheus:
    ensure: present

prometheus::scrape_configs:
  - job_name: 'sflow'
    scrape_interval: '10s'
    scrape_timeout: '10s'
    metrics_path: '/prometheus/metrics/ALL/ALL/txt'
    static_configs:
      - targets:
          - "%{hiera('netcfg_mgmt_net_c0')}.55:8008"
        labels:
          alias: 'sflow'
