---
include:
  default:
    - profile::openstack::volume
    - profile::openstack::volume::api
    - profile::openstack::volume::scheduler
    - profile::openstack::volume::storage
    - profile::openstack::openrc
    - profile::logging::rsyslog::client

profile::base::common::packages:
  'python-openstackclient': {}
  'python2-oslo-policy': {}
  'python2-keystonemiddleware': {}
  'bash-completion': {}
  'bash-completion-extras': {}
  'jq': {}

profile::openstack::openrc::password:     "%{hiera('cinder_api_password')}"
profile::openstack::openrc::username:     'cinder'
profile::openstack::openrc::project_name: 'services'

profile::openstack::volume::type:
  rbd:
    set_key: 'volume_backend_name'
    set_value: 'rbd-volumes'
    os_tenant_name: 'services'
    os_password: "%{hiera('cinder_api_password')}"
    os_username: 'cinder'
    os_region_name: "%{location}"
    os_auth_url: "%{hiera('endpoint__identity__internal')}/v2.0"

profile::openstack::volume::manage_quotas: true

profile::openstack::volume::backend::rbd:
  rbd-volumes:
    rbd_pool: 'volumes'
    rbd_user: 'cinder'
    rbd_secret_uuid: "%{hiera('client.cinder::secret')}"

cinder::backends::enabled_backends:
  - rbd-volumes

# openstack-cinder creates a sudoers.d file used to
# load backend drivers
sudo::purge: false

# Enable extra yum repo
profile::base::yumrepo::repo_hash:
  rdo-release:
    ensure: present
  ceph-%{hiera('ceph_version')}:
    ensure: present

# Volume nodes need only cinder keys
ceph::profile::params::client_keys:
  'client.cinder':
    secret: "%{hiera('client_cinder::secret')}"
    mode: '0600'
    user: 'cinder'
    group: 'cinder'
    cap_mon: 'allow r'
    cap_osd: 'allow class-read object_prefix rbd_children, allow rwx pool=volumes, allow rwx pool=vms, allow rwx pool=images'
