---
include:
  default:
    - profile::openstack::volume
    - profile::openstack::volume::api
    - profile::openstack::volume::scheduler
    - profile::openstack::volume::storage
    - profile::openstack::openrc
    - profile::logging::rsyslog::client

profile::base::common::packages:
  'python-openstackclient': {}
  'python2-oslo-policy': {}
  'python2-keystonemiddleware': {}
  'bash-completion': {}
  'bash-completion-extras': {}
  'jq': {}
  'openstack-selinux': {}

profile::base::selinux::manage_selinux:   false
profile::openstack::openrc::password:     "%{hiera('cinder_api_password')}"
profile::openstack::openrc::username:     'cinder'
profile::openstack::openrc::project_name: 'services'

profile::openstack::volume::type:
  rbd:
    visibility: "public"
    properties:
      - 'volume_backend_name=rbd-volumes'
#  rbd-ssd:
#    visibility: "private"
#    properties:
#      - 'volume_backend_name=rbd-ssd'

profile::openstack::volume::manage_telemetry: true
profile::openstack::volume::manage_quotas:    true

profile::openstack::volume::backend::rbd:
  rbd-volumes:
    rbd_pool: 'volumes'
    rbd_user: 'cinder'
    rbd_secret_uuid: "%{hiera('client.cinder::secret')}"
    extra_options:
      rbd-volumes/report_discard_supported:
        value: 'True'

cinder::backends::enabled_backends:
  - rbd-volumes

# openstack-cinder creates a sudoers.d file used to
# load backend drivers
sudo::purge: false

# Enable extra yum repo
profile::base::yumrepo::repo_hash:
  rdo-release:
    ensure: present
  ceph-%{hiera('ceph_version')}:
    ensure: present

# Volume nodes need only cinder keys
ceph::profile::params::client_keys:
  'client.cinder':
    secret: "%{hiera('client_cinder::secret')}"
    mode: '0600'
    user: 'cinder'
    group: 'cinder'
    cap_mon: 'profile rbd'
    cap_osd: 'profile rbd pool=volumes, profile rbd pool=vms, profile rbd pool=images'
