---
include:
  bootstrap:
    - profile::application::openssl

profile::application::openssl::manage_ca_cert:  true
profile::application::openssl::certs:
  "%{::hostname}.%{hiera('domain_trp')}":
    cn:     "%{::hostname}.%{hiera('domain_trp')}"
    altnames:
      - "%{::hostname}.%{hiera('domain_trp')}"
      - "%{::fqdn}"

# FIXME:sensu-go

# Plugins not avaiable as assets for el8
# sensu::plugins::plugins:
#   sensu-plugins-mysql:
#     version: 3.2.0

sensu::agent::subscriptions:
  - 'base'
  - 'nodes'
  - 'metrics'

profile::monitoring::sensu::agent::checks:
  check-mysql-alive:
    command:                "check-mysql-alive.rb -h localhost -s /var/lib/mysql/mysql.sock"
    interval:               60
    subscriptions:          ['entity:%{::hostname}']
    handlers:               ['default']
#    provider:               'sensu_api'
    runtime_assets:
    - sensu-plugins/sensu-plugins-mysql
