---
include:
  default:
    - profile::monitoring::netdata

profile::monitoring::netdata::manage_firewall:  true
profile::database::mariadb::backuptopdir:       '/tmp/'

# Netdata access
profile::database::mariadb::users:
  'netdata@localhost':
    ensure: present

profile::database::mariadb::grants:
  'netdata@localhost/*.*':
    privileges: ['USAGE']
    table:      '*.*'
    user:       'netdata@localhost'
