---
include:
  default:
    - profile::openstack::designate
    - profile::logging::rsyslog::client

profile::openstack::designate::manage_designate: true
profile::openstack::designate::manage_designate_bind: true

# 1. We want /usr/bin/openstack (not sure if it's strictly needed)
# 2. designate-manage requires python2-oslo-reports and python2-suds
# 3. pool-manager requires python-tooz
# 4. we use memcache as pool manager cache
profile::base::common::packages:
  'python-openstackclient': {}
  'python2-oslo-reports': {}
  'python2-suds': {}
  'python-tooz': {}
  'memcached': {}

# Don't purge sudo stuff
sudo::purge: false

# Override repo "rdo-release": liberty -> mitaka
openstack_version: 'mitaka'

# Enable extra yum repo
profile::base::yumrepo::repo_hash:
  rdo-release:
    ensure: present

#---------------------------------------------------------------------
# Pools
#---------------------------------------------------------------------
profile::openstack::designate::my_pools:
  '794ccc2c-d751-44fe-b57f-8894c9f5c842':
    nameservers:
      - '072b6384-c7d0-4685-8e89-39093ff4bf5f'
    targets:
      - 'b81c1479-c6df-4f75-b793-96d0b2a3de51'

#---------------------------------------------------------------------
# Nameservers
#---------------------------------------------------------------------
profile::openstack::designate::my_nameservers:
  '072b6384-c7d0-4685-8e89-39093ff4bf5f':
    port: 53
    host: '127.0.0.1'

#---------------------------------------------------------------------
# Pool targets
#---------------------------------------------------------------------
profile::openstack::designate::my_targets:
  'b81c1479-c6df-4f75-b793-96d0b2a3de51':
    options: 'rndc_host: 127.0.0.1, rndc_port: 953, rndc_config_file: /etc/rndc.conf, rndc_key_file: /etc/rndc.key, port: 53, host: 127.0.0.1'
    masters:
      - '127.0.0.1:5354'
    type: 'bind9'


# named huskeliste
#sed -i -e "s/listen-on port.*/listen-on port 53 { 127.0.0.1; 172.31.16.23; };/" /etc/named.conf
#sed -i '/^options.*/i \
#include "/etc/rndc.key"; \
#controls { \
#        inet 127.0.0.1 allow { localhost; } keys { "rndc-key"; }; \
#};' /etc/named.conf
#sed -i '/allow-query.*/d' /etc/named.conf
#sed -i '/recursion.*/d' /etc/named.conf
#sed -i '/^options.*/a \
#        allow-new-zones yes; \
#        allow-query { any; }; \
#        recursion no;' /etc/named.conf
#cat << EOF > /etc/rndc.conf
#include "/etc/rndc.key";
#options {
#        default-key "rndc-key";
#        default-server 127.0.0.1;
#        default-port 953;
#};
#EOF
#
#setsebool -P named_write_master_zones on
#chmod g+w /var/named
#chown named:named /etc/rndc.conf
#chown named:named /etc/rndc.key
#chmod 600 /etc/rndc.key
#
