---
accounts::accounts:
  'vagrant':
    ensure: present
  'iaas':
    ensure: absent

profile::application::git::settings:
  hostname: "login%{::hostid}"

ssh::server::options:
  'Match User vagrant':
     AuthenticationMethods: 'publickey'

# Himlar bootstrap
profile::bootstrap::himlar::manage_bootstrap_scripts: true
himlar_bootstrap::tftp_install:
  '%{location}-controller-01':
    domain:           '%{domain}'
    dhcp_interface:   'eth1'
    dhcp_range_start: "%{hiera('netcfg_netpart_mgmt')}.200"
    dhcp_range_end:   "%{hiera('netcfg_netpart_mgmt')}.250"
    dhcp_gateway:     "%{hiera('netcfg_netpart_mgmt')}.1"

profile::base::login::db_servers:
  vagrant-db-01:
    hour:     '*'
    minute:   '20'
    command:  '/usr/local/sbin/db-dump.sh dev-db-01 >/dev/null'
