---

# In the vagrant environment the master role include the console(proxy) functionality
# to conserve resources

include:
  default:
    - profile::logging::rsyslog::client
    - profile::openstack::compute::consoleproxy
    - profile::application::sslcert
    - profile::messaging::rabbitmq
    - profile::openstack::designate
    
profile::messaging::rabbitmq::manage_rsyslog: true

calico::compute_manage_bird_config:   false
calico::reflector::bird_template:     'calico/compute/bird.conf.erb'
calico::reflector::bird6_template:    'calico/compute/bird6.conf.erb'
calico::reflector: true

rabbitmq::cluster_nodes:
  - 'vagrant-master-01'

profile::openstack::network::controller::neutron_nova_insecure: true

profile::openstack::resource::networks:
  public:
    name: 'public'
    admin_state_up: true
    shared: true
    tenant_name: 'openstack'
    provider_network_type: 'local'

profile::openstack::resource::subnets:
  public:
    name: 'public'
    cidr: '172.31.24.0/24'
    ip_version: '4'
    allocation_pools:
      - 'start=172.31.24.200,end=172.31.24.250'
    gateway_ip: '172.31.24.1'
    dns_nameservers:
      - '129.177.6.54'
      - '129.177.12.31'
    network_name: 'public'
    tenant_name: 'openstack'


# consoleproxy data (normally in 'console.yaml')

profile::openstack::compute::consoleproxy::spice: true
console_ssl_files:  "vagrant-master-01.%{hiera('domain_public')}"

nova::config::nova_config:
    DEFAULT/cert:
      value: "/etc/pki/tls/certs/%{hiera('console_ssl_files')}.crt"
    DEFAULT/key:
      value: "/etc/pki/tls/private/%{hiera('console_ssl_files')}.key"

# Default rabbitmq server in vagrant is master node
profile::messaging::rabbitmq::users:
  nova:
    password: "%{hiera('nova::rabbit_password')}"
  cinder:
    password: "%{hiera('cinder::rabbit_password')}"
  neutron:
    password: "%{hiera('neutron::rabbit_password')}"
#  designate:
#    password: "%{hiera('designate::rabbit_password')}"
#  glance:
#    password: "%{hiera('glance::rabbit_password')}"

profile::messaging::rabbitmq::vhosts:
  nova: {}
  cinder: {}
  neutron: {}
#  designate: {}
#  glance: {}

profile::messaging::rabbitmq::user_permissions:
  'nova@nova':
    configure_permission: '.*'
    write_permission:     '.*'
    read_permission:      '.*'
  'cinder@cinder':
    configure_permission: '.*'
    write_permission:     '.*'
    read_permission:      '.*'
  'neutron@neutron':
    configure_permission: '.*'
    write_permission:     '.*'
    read_permission:      '.*'
#  'designate@designate':
#    configure_permission: '.*'
#    write_permission:     '.*'
#    read_permission:      '.*'
#  'glance@glance':
#    configure_permission: '.*'
#    write_permission:     '.*'
#    read_permission:      '.*'

profile::messaging::rabbitmq::policy:
  ha-all@nova:
    pattern:                '.*'
    priority:               0
    applyto:                'all'
    definition:
      'ha-mode':            'all'
      'ha-sync-mode':       'automatic'
