---
include:
  default:
    - profile::openstack::designate
    - profile::logging::rsyslog::client

profile::openstack::designate::manage_designate: true

# 1. We want /usr/bin/openstack (not sure if it's strictly needed)
# 2. designate-manage requires python2-oslo-reports and python2-suds
# 3. pool-manager requires python-tooz
# 4. we use memcache as pool manager cache
profile::base::common::packages:
  'python-openstackclient': {}
  'python2-oslo-reports': {}
  'python2-suds': {}
  'python-tooz': {}
  'memcached': {}

# Don't purge sudo stuff
sudo::purge: false

# Override repo "rdo-release": liberty -> mitaka
openstack_version: 'mitaka'

# Enable extra yum repo
profile::base::yumrepo::repo_hash:
  rdo-release:
    ensure: present

#---------------------------------------------------------------------
# Pools
#---------------------------------------------------------------------
profile::openstack::designate::my_pools:
  '794ccc2c-d751-44fe-b57f-8894c9f5c842':
    nameservers:
      - '00000000-0000-0000-0000-000000000001'
      - '00000000-0000-0000-0000-000000000002'
    targets:
      - 'b81c1479-c6df-4f75-b793-96d0b2a3de51'

#---------------------------------------------------------------------
# Nameservers
#---------------------------------------------------------------------
profile::openstack::designate::my_nameservers:
  '00000000-0000-0000-0000-000000000001':
    port: 53
    host: "%{hiera('service__address__dns01')}"
  '00000000-0000-0000-0000-000000000002':
    port: 53
    host: "%{hiera('service__address__dns02')}"

#---------------------------------------------------------------------
# Pool targets
#---------------------------------------------------------------------
profile::openstack::designate::my_targets:
  'b81c1479-c6df-4f75-b793-96d0b2a3de51':
    options: "rndc_host: %{hiera('service__address__designate_api')}, rndc_port: 953, rndc_config_file: /etc/rndc.conf, rndc_key_file: /etc/rndc.key, port: 53, host: %{hiera('service__address__designate_api')}"
    masters:
      - "%{hiera('service__address__designate_api')}:5354"
    type: 'bind9'
