---
# Public and internal zones
profile::dns::ns::internal_zone: "vagrant.iaas.intern"
profile::dns::ns::public_zone:   "vagrant.iaas.intern"

# NS servers in zone file (with NS records)
profile::dns::ns::ns_master: "ns.%{hiera('profile::dns::ns::public_zone')}"
profile::dns::ns::ns_slaves:
  - "tux.uio.no"
  - "kipepeo.uio.no"

# Forward zones, for which the name server is authoritative
profile::dns::ns::fw_zones:
  internal:
    zone:     "%{hiera('profile::dns::ns::public_zone')}"
    filename: "%{hiera('profile::dns::ns::zonedir')}/%{hiera('profile::dns::ns::public_zone')}"
    ns_a_records:
      'ns': "%{hiera('public__address__ns')}"
    ns_aaaa_records:
      'ns': "%{hiera('public6__address__ns')}"

# Manual zones, maintained manually
profile::dns::ns::manual_zones:
  frontend:
    zone:     "uh-iaas.no"
    filename: "%{hiera('profile::dns::ns::zonedir')}/uh-iaas.no"
    ns_a_records:
      'ns': "%{hiera('public__address__ns')}"
    ns_aaaa_records:
      'ns': "%{hiera('public6__address__ns')}"

# Reverse zones, for which the name server is authoritative
profile::dns::ns::ptr_zones:
  internal:
    cidr:     "172.31.0.0/16"
    origin:   "31.172.in-addr.arpa"
    filename: "%{hiera('profile::dns::ns::zonedir')}/31.172.in-addr.arpa"
  public:
    cidr:     "192.168.0/16"
    origin:   "168.192.in-addr.arpa"
    filename: "%{hiera('profile::dns::ns::zonedir')}/168.192.in-addr.arpa"
  ipv6:
    cidr:     "fc00::/7"
    origin:   "c.f.ip6.arpa"
    filename: "%{hiera('profile::dns::ns::zonedir')}/c.f.ip6.arpa"

# TEST
profile::dns::ns::host_is_ns_master: true
