---
# Public and internal zones
profile::dns::ns::internal_zone: "vagrant.iaas.intern"
profile::dns::ns::public_zone:   "vagrant.iaas.intern"

# NS servers in zone file (with NS records)
profile::dns::ns::ns_master: "ns.%{hiera('profile::dns::ns::public_zone')}"
#profile::dns::ns::ns_slaves:
#  - "tux.uio.no"

# Master server for master-slave configuration
profile::dns::ns::ns_master_ip_addresses:
  - "%{hiera('public__address__ns')}"
  - "%{hiera('public6__address__ns')}"
#  - '158.37.63.251'        # ns.osl.uh-iaas.no IPv4
#  - '2001:700:2:82ff::251' # ns.osl.uh-iaas.no IPv6

# Slave servers for master-slave configuration
profile::dns::ns::ns_slave_ip_addresses:
  - '158.39.77.251'        # ns.bgo.uh-iaas.no IPv4
  - '2001:700:2:83ff::251' # ns.bgo.uh-iaas.no IPv6

# Forward zones, for which the name server is authoritative
profile::dns::ns::fw_zones:
  internal:
    zone:     "%{hiera('profile::dns::ns::public_zone')}"
    filename: "pz/%{hiera('profile::dns::ns::public_zone')}"
    ns_a_records:
      'ns': "%{hiera('public__address__ns')}"
    ns_aaaa_records:
      'ns': "%{hiera('public6__address__ns')}"

# Manual zones, maintained manually
#profile::dns::ns::manual_zones:
#  frontend:
#    zone:     "uh-iaas.no"
#    filename: "pz/uh-iaas.no"

# Reverse zones, for which the name server is authoritative
profile::dns::ns::ptr_zones:
  mgmt:
    cidr:     "172.31.0.0/24"
    origin:   "0.31.172.in-addr.arpa"
    filename: "pz/0.31.172.in-addr.arpa"
  transport:
    cidr:     "172.31.8.0/24"
    origin:   "8.31.172.in-addr.arpa"
    filename: "pz/8.31.172.in-addr.arpa"
  public:
    cidr:     "192.168.0.0/24"
    origin:   "0.168.192.in-addr.arpa"
    filename: "pz/0.168.192.in-addr.arpa"
  ipv6:
    cidr:     "fc00::/7"
    origin:   "c.f.ip6.arpa"
    filename: "pz/c.f.ip6.arpa"

# Secondary forward zones, for which this ns is slave
profile::dns::ns::fw_slave_zones:
  test02_internal:
    zone: "%{hiera('profile::dns::ns::internal_zone')}"
    filename: "sz/%{hiera('profile::dns::ns::internal_zone')}"
  test02_frontend:
    zone: "%{hiera('profile::dns::ns::public_zone')}"
    filename: "sz/%{hiera('profile::dns::ns::public_zone')}"

# Secondary reverse zones, for which this ns is slave
profile::dns::ns::fw_slave_zones:
  test02_mgmt:
    cidr: "172.28.32.0/24"
    origin: "32.28.172.in-addr.arpa"
    filename: "sz/32.28.172.in-addr.arpa"
