---
star_api_ssl_pem: "api.%{hiera('domain_public')}.pem"
api_ssl_pem:      "status.%{hiera('domain_public')}.pem"
status_ssl_pem:   "status.%{hiera('domain_public')}.pem"
console_ssl_pem:  "status.%{hiera('domain_public')}.pem" #FIXME (cert)
access_ssl_pem:   "status.%{hiera('domain_public')}.pem" #FIXME (cert)

profile::highavailability::loadbalancing::haproxy::allow_from_network:
  - '129.177.6.133/32'  # bgo-login
  - '129.177.31.96/27'  # test01
  - '129.177.10.111/32' # anders
  - '129.177.10.189/32' # tor
  - '129.177.10.212/32' # raymond
  - '129.240.202.12/32' # trond
  - '129.240.6.14/32'   # mikael
  - '129.240.202.64/32' # tannaz


profile::highavailability::loadbalancing::haproxy::haproxy_balancermembers:
  network:
      server_names:       ['%{::location}-network-02']
      ipaddresses:        ["%{hiera('netcfg_trp_netpart')}.72"]
