---
profile::base::selinux::manage_selinux:         false

# FIXME:sensu-go
sensu::agent::subscriptions:
  - 'base'
  - 'nodes'
  - 'metrics'

profile::monitoring::sensu::agent::checks:
  ceph-check:
    command:                "ceph-health.sh -n client.sensu"
    interval:               60
    subscriptions:          ['entity:%{::hostname}']
    handlers:               ['default']
    round_robin:            true
    runtime_assets:
    - thorko/sensu-check-ceph

# FIXME:ceph-metric
include:
  default:
    - profile::monitoring::telegraf

profile::monitoring::telegraf::enable_telegraf:     true
profile::monitoring::telegraf::outputs:
  influxdb_v2:
    options:
      - urls: ["https://%{hiera('mgmt__address__influx')}:8086"]
        tls_ca: '/etc/puppetlabs/puppet/ssl/certs/ca.pem'
        token: "%{hiera('influxdb_admin_token')}"
        organization: "%{hiera('profile::monitoring::influxdb::org')}"
        bucket: 'ceph'
        insecure_skip_verify: true

profile::monitoring::telegraf::inputs:
  prometheus:
    options:
      - urls: ["http://%{::ipaddress_mgmt1}:9283/metrics"]
        metric_version: 2
  # ceph:
  #   options:
  #     - interval: '1m'
  #       socket_dir: "/var/run/ceph"
  #       ceph_binary: "/usr/bin/ceph"
  #       socket_suffix: "asok"
  #       mon_prefix: "ceph-mon"

profile::base::yumrepo::repo_hash:
  influxdb:
    ensure: present
