---
include:
  default:
    - profile::base::tuned

named_interfaces::config:
  mgmt:
    - bond0
  trp:
    - bond0.912
  live:
    - bond0.912

profile::base::network::network_auto_opts:
  mgmt:
    'defroute': 'no'
  trp:
    'ipv6init': 'yes'
    'bonding_opts': 'mode=balance-alb miimon=100'

profile::base::network::network_auto_bonding:
  trp:
    em1: {}
    em2: {}

ntp::servers:
  - 172.28.0.100
  - 172.28.0.101
  - 172.28.0.102

# Add custom routing table for private network to NAT
profile::base::network::routes:
  'bond0.912':
    'ipaddress': [ '0.0.0.0', '0.0.0.0', ]
    'netmask':   [ '0.0.0.0', '0.0.0.0', ]
    'gateway':   [ "%{hiera('netcfg_priv_gateway')}", "%{hiera('netcfg_trp_gateway')}" ]
    'table':     [ 'private', 'main', ]
profile::base::network::routing_tables:
  'private':
    'table_id':  '240'
profile::base::network::rules:
  'bond0.912':
    iprule: [ "from %{hiera('netcfg_priv_network')} lookup private", ]
profile::base::network::manage_neutron_blackhole: true

# remove when telemetry/ceilometer is up in all environments and move to common
profile::openstack::compute::manage_telemetry: true

# Set tuned profile to "virtual-host"
profile::base::tuned::manage_tuned:  true
profile::base::tuned::tuned_profile: 'virtual-host'

# FIXME - temp with calico 3.8
# Enable extra yum repo
profile::base::yumrepo::repo_hash:
  rdo-release:
    ensure: present
#    exclude: 'openstack-neutron openstack-neutron-common python-neutron'
  calico31:
    ensure: absent
  calico37:
    ensure: absent
  calico38:
    ensure: present
    exclude: 'dnsmasq'
  ceph-%{hiera('ceph_version')}:
    ensure: present
  centos-qemu-ev:
    ensure: present
  epel: # should be absent when using RDO, but whitelist can also work
    ensure:   present
    includepkgs: 'bird bird6 htop bash-completion-extras lttng-ust userspace-rcu libbabeltrace leveldb liboath py-bcrypt python2-bcrypt libsmbios smbios-utils-bin'
