---
himlar_bootstrap::virt_install:
  '%{location}-admin-01':
    domain:          '%{domain}'
    libvirt_pool:    'dirpool'
    libvirt_network: 'directnet'
    install_ip:      '172.28.0.11'
    install_netmask: '255.255.255.0'
    install_gateway: '172.28.0.10'
    vm_console:      false
    use_dhcp:        false

profile::virtualization::libvirt::networks:
  directnet:
    ensure:              enabled
    autostart:           true
    forward_mode:        bridge
    bridge:              br0
  trpnet:
    ensure:              enabled
    autostart:           true
    forward_mode:        bridge
    bridge:              br1
  oobnet:
    ensure:              enabled
    autostart:           true
    forward_mode:        bridge
    bridge:              br2
