---
profile::base::common::manage_lvm: true

# temp el8 fix for logger
logrotate::rules:
  syslog:
    ensure:         absent
  rsyslog:
    path:           ['/var/log/cron', '/var/log/maillog', '/var/log/messages', '/var/log/secure', '/var/log/spooler']
    rotate:         10
    rotate_every:   daily
    postrotate:     '/bin/kill -HUP `cat /var/run/rsyslogd.pid 2> /dev/null` 2> /dev/null || true'
    dateext:        true
    sharedscripts:  true
    missingok:      true
    compress:       true
  openstack:
    path:           '/opt/log/*.log'
    rotate:         7
    postrotate:     '/bin/kill -HUP `cat /var/run/syslogd.pid 2> /dev/null` 2> /dev/null || true'
    sharedscripts:  true
    missingok:      true
    rotate_every:   daily
    compress:       true
  messages:
    path:           '/opt/log/*/messages'
    rotate:         7
    postrotate:     '/bin/kill -HUP `cat /var/run/syslogd.pid 2> /dev/null` 2> /dev/null || true'
    sharedscripts:  true
    missingok:      true
    rotate_every:   daily
    compress:       true

