---
# Authoritative name servers must have a public interface
profile::base::network::manage_dummy: true

# Public and internal zones
profile::dns::ns::internal_zone: "test01.uhdc.no"
profile::dns::ns::public_zone:   "test.iaas.uib.no"

# Name servers in zone file
profile::dns::ns::ns_master: "ns.%{hiera('profile::dns::ns::public_zone')}"
#profile::dns::ns::ns_slaves:
#  - "ns.test.iaas.uio.no"

# Master server for master-slave configuration
#profile::dns::ns::ns_master_ip_addresses:
#  - '192.168.0.251'         # ns.test.iaas.uio.no IPv4
#  - 'fc00:700:100:200::251' # ns.test.iaas.uio.no IPv6

# Slave servers for master-slave configuration
#profile::dns::ns::ns_slave_ip_addresses:
#  - '192.168.0.251'         # ns.test.iaas.uio.no IPv4
#  - 'fc00:700:100:200::251' # ns.test.iaas.uio.no IPv6

# Forward zones, for which the name server is authoritative
profile::dns::ns::fw_zones:
  internal:
    zone: "%{hiera('profile::dns::ns::internal_zone')}"
    filename: "pz/%{hiera('profile::dns::ns::internal_zone')}"
  public:
    zone: "%{hiera('profile::dns::ns::public_zone')}"
    filename: "pz/%{hiera('profile::dns::ns::public_zone')}"
    ns_a_records:
      'ns': "%{hiera('public__address__ns')}"
    ns_aaaa_records:
      'ns': "%{hiera('public6__address__ns')}"

# Reverse zones, for which the name server is authoritative
profile::dns::ns::ptr_zones:
  mgmt:
    cidr: "172.28.0.0/24"
    origin: "0.28.172.in-addr.arpa"
    filename: "pz/0.28.172.in-addr.arpa"
  transport:
    cidr: "172.30.0.0/24"
    origin: "0.30.172.in-addr.arpa"
    filename: "pz/0.30.172.in-addr.arpa"
  public:
    cidr: "129.177.31.0/24"
    origin: "31.177.129.in-addr.arpa"
    filename: "pz/31.177.129.in-addr.arpa"
  ipv6:
    cidr: "2001:700:200:916::/64"
    origin: "6.1.9.0.0.0.2.0.0.0.7.0.1.0.0.2.ip6.arpa"
    filename: "pz/6.1.9.0.0.0.2.0.0.0.7.0.1.0.0.2.ip6.arpa"

# Secondary forward zones, for which this ns is slave
#profile::dns::ns::fw_slave_zones:
#  test02_internal:
#    zone: 'test02.uhdc.no'
#    filename: "sz/test02.uhdc.no"
#  test02_public:
#    zone: 'test.iaas.uio.no'
#    filename: "sz/test.iaas.uio.no"

# Secondary reverse zones, for which this ns is slave
#profile::dns::ns::ptr_slave_zones:
#  test02_mgmt:
#    cidr: "172.28.32.0/24"
#    origin: "32.28.172.in-addr.arpa"
#    filename: "sz/32.28.172.in-addr.arpa"
#  test02_transport:
#    cidr: "172.30.32.0/24"
#    origin: "32.30.172.in-addr.arpa"
#    filename: "sz/32.30.172.in-addr.arpa"
#  test02_public:
#    cidr: "10.100.200.0/24"
#    origin: "200.100.10.in-addr.arpa"
#    filename: "sz/200.100.10.in-addr.arpa"
#  test02_ipv6:
#    cidr: "fd34::/7"
#    origin: "4.3.d.f.ip6.arpa"
#    filename: "sz/4.3.d.f.ip6.arpa"
