---
# Authoritative name servers must have a public interface
profile::base::network::manage_dummy: true

# Public and internal zones
profile::dns::ns::internal_zone: "test01.uhdc.no"
profile::dns::ns::public_zone:   "test.iaas.uib.no"

# Name servers in zone file
profile::dns::ns::name_servers:
  - "ns.%{hiera('profile::dns::ns::public_zone')}"

# Forward zones, for which the name server is authoritative
profile::dns::ns::fw_zones:
  internal:
    zone: "%{hiera('profile::dns::ns::internal_zone')}"
    filename: "pz/%{hiera('profile::dns::ns::internal_zone')}"
  frontend:
    zone: "%{hiera('profile::dns::ns::public_zone')}"
    filename: "pz/%{hiera('profile::dns::ns::public_zone')}"

# Reverse zones, for which the name server is authoritative
profile::dns::ns::ptr_zones:
  mgmt:
    cidr: "172.28.0.0/24"
    origin: "0.28.172.in-addr.arpa"
    filename: "pz/0.28.172.in-addr.arpa"
  transport:
    cidr: "172.30.0.0/24"
    origin: "0.30.172.in-addr.arpa"
    filename: "pz/0.30.172.in-addr.arpa"
  public:
    cidr: "129.177.31.64/27"
    origin: "64.31.177.129.in-addr.arpa"
    filename: "pz/64.31.177.129.in-addr.arpa"
  ipv6:
    cidr: "2001:700:200:916::/64"
    origin: "6.1.9.0.0.0.2.0.0.0.7.0.1.0.0.2.ip6.arpa"
    filename: "pz/6.1.9.0.0.0.2.0.0.0.7.0.1.0.0.2.ip6.arpa"
