---
status_ssl_pem:   "api.%{hiera('domain_public')}.pem" #FIXME (status cert)

# FIXME (mgmt1 -> public1)
profile::highavailability::loadbalancing::haproxy::haproxy_listens:
  identity:
    options:
      http-request:   'add-header X-Forwarded-Proto https if { ssl_fc }'
    bind:
      "%{::ipaddress_mgmt1}:5000":  ['ssl', 'crt', "%{hiera('star_api_ssl_pem')}", 'crt', "%{hiera('api_ssl_pem')}"]
  compute:
    options:
      http-request:   'add-header X-Forwarded-Proto https if { ssl_fc }'
    bind:
      "%{::ipaddress_mgmt1}:8774":  ['ssl', 'crt', "%{hiera('star_api_ssl_pem')}"]
  volume:
    options:
      http-request:   'add-header X-Forwarded-Proto https if { ssl_fc }'
    bind:
      "%{::ipaddress_mgmt1}:8776":  ['ssl', 'crt', "%{hiera('star_api_ssl_pem')}"]
  image:
    options:
      http-request:   'add-header X-Forwarded-Proto https if { ssl_fc }'
    bind:
      "%{::ipaddress_mgmt1}:9292":  ['ssl', 'crt', "%{hiera('star_api_ssl_pem')}"]
  network:
    options:
      http-request:   'add-header X-Forwarded-Proto https if { ssl_fc }'
    bind:
      "%{::ipaddress_mgmt1}:9696":  ['ssl', 'crt', "%{hiera('star_api_ssl_pem')}"]
  name:
    options:
      http-request:   'add-header X-Forwarded-Proto https if { ssl_fc }'
    bind:
      "%{::ipaddress_mgmt1}:9001":  ['ssl', 'crt', "%{hiera('star_api_ssl_pem')}"]
  status:
    options:
      http-request:   'add-header X-Forwarded-Proto https if { ssl_fc }'
      redirect:       'scheme https if !{ ssl_fc }'
    bind:
      "%{::ipaddress_mgmt1}:443":  ['ssl', 'crt', "%{hiera('status_ssl_pem')}"]
      "%{::ipaddress_mgmt1}:80": []
  monitor:
    options:
      stats:
        - 'enable'
        - 'hide-version'
        - 'realm Sensu\ Monitor\ Stats'
        - 'uri /haproxy_stats '
    bind:
      '127.0.0.1:9000': []
