---
status_ssl_pem:   "star.%{hiera('domain_public')}.pem" #FIXME (status cert) star/api
console_ssl_pem:  "star.%{hiera('domain_public')}.pem"
access_ssl_pem:   "star.%{hiera('domain_public')}.pem"

profile::highavailability::loadbalancing::haproxy::haproxy_balancermembers:
  network:
    server_names:       ['%{::location}-network-02']
    ipaddresses:        ["%{hiera('netcfg_trp_netpart')}.72"]
