---
include:
  kickstart:
    - profile::monitoring::sensu::agent

named_interfaces::config:
  mgmt:
     - em3
  trp:
     - bond1
  transport:
     - bond1
  service:
     - bond1

ntp::servers:
  - 172.28.32.100
  - 172.28.32.101
  - 172.28.32.102

profile::monitoring::sensu::agent::enable_agent:  true

puppet::cron_cmd: "if [ -e /root/proxy.sh ] ; then source /root/proxy.sh ; fi ; \
  /usr/bin/env puppet agent --config %{puppet::dir}/puppet.conf --onetime --no-daemonize"

# Add custom routing table for private network to NAT
profile::base::network::routes:
  'bond1':
    'ipaddress': [ '0.0.0.0', ]
    'netmask':   [ '0.0.0.0', ]
    'gateway':   [ "%{hiera('netcfg_priv_gateway')}", ]
    'table':     [ 'private', ]
profile::base::network::routing_tables:
  'private':
    'table_id':  '240'
profile::base::network::rules:
  'bond1':
    iprule: [ "from %{hiera('netcfg_priv_network')} lookup private", ]

################ TEMP DATA - SHOULD BE FIXED IN COMMON #########################
calico::compute::bird_template: 'profile/bird/bird.conf.erb'

nova::debug: true
