---
# Authoritative name servers must have a public interface
profile::base::network::manage_dummy: true

# Public and internal zones
profile::dns::ns::internal_zone: "test02.uhdc.no"
profile::dns::ns::public_zone:   "test.iaas.uio.no"

# Name servers in zone file
profile::dns::ns::name_servers:
  - "ns.%{hiera('profile::dns::ns::public_zone')}"

# Forward zones, for which the name server is authoritative
profile::dns::ns::fw_zones:
  internal:
    zone: "%{hiera('profile::dns::ns::internal_zone')}"
    filename: "pz/%{hiera('profile::dns::ns::internal_zone')}"
  frontend:
    zone: "%{hiera('profile::dns::ns::public_zone')}"
    filename: "pz/%{hiera('profile::dns::ns::public_zone')}"

# Reverse zones, for which the name server is authoritative
profile::dns::ns::ptr_zones:
  mgmt:
    cidr: "172.28.32.0/24"
    origin: "32.28.172.in-addr.arpa"
    filename: "pz/32.28.172.in-addr.arpa"
  transport:
    cidr: "172.30.32.0/24"
    origin: "32.30.172.in-addr.arpa"
    filename: "pz/32.30.172.in-addr.arpa"
  public:
    cidr: "10.100.200.0/24"
    origin: "200.100.10.in-addr.arpa"
    filename: "pz/200.100.10.in-addr.arpa"
  ipv6:
    cidr: "fd34::/7"
    origin: "4.3.d.f.ip6.arpa"
    filename: "pz/4.3.d.f.ip6.arpa"
