---
# Authoritative name servers must have a public interface
profile::base::network::manage_dummy: true

# Our internal zone
profile::dns::ns::internal_zone: "test02.uhdc.no"

# Name servers in zone file
profile::dns::ns::name_servers:
  - "ns.%{hiera('profile::dns::ns::internal_zone')}"
  - "ns.test01.uhdc.no"

# Forward zones, for which the name server is authoritative
profile::dns::ns::fw_zones:
  internal:
    zone: "%{hiera('profile::dns::ns::internal_zone')}"
    filename: "%{hiera('profile::dns::ns::zonedir')}/%{hiera('profile::dns::ns::internal_zone')}"
  frontend:
    zone: "iaas.uio.no"
    filename: "%{hiera('profile::dns::ns::zonedir')}/iaas.uio.no"

# Reverse zones, for which the name server is authoritative
profile::dns::ns::ptr_zones:
  internal:
    cidr: "172.28.0.0/16"
    origin: "28.172.in-addr.arpa"
    filename: "%{hiera('profile::dns::ns::zonedir')}/28.172.in-addr.arpa"
  public:
    cidr: "10.100.0.0/16"
    origin: "100.10.in-addr.arpa"
    filename: "%{hiera('profile::dns::ns::zonedir')}/100.10.in-addr.arpa"
  ipv6:
    cidr: "fd34::/7"
    origin: "4.3.d.f.ip6.arpa"
    filename: "%{hiera('profile::dns::ns::zonedir')}/4.3.d.f.ip6.arpa"
