---
# Temporary: Forward everything to UiO resolvers
profile::dns::ns::forward_everything: true
profile::dns::ns::forwarders:
  - "129.240.2.40"
  - "129.240.2.27"
  - "129.240.2.3"

# Reverse zones. Only zones that are "internal". Requests for records
# in these zones will be forwarded to the authoritative DNS server
profile::dns::ns::ptr_zones:
  mgmt:
    cidr: "172.28.32.0/24"
    origin: "32.28.172.in-addr.arpa"
  transport:
    cidr: "172.30.32.0/24"
    origin: "32.30.172.in-addr.arpa"
  public:
    cidr: "10.100.200.0/24"
    origin: "200.100.10.in-addr.arpa"
  ipv6:
    cidr: "fd34::/7"
    origin: "4.3.d.f.ip6.arpa"

profile::dns::ns::allowed_nets:
  - '172.16.0.0/12;         # internal rfc1918'
  - '10.0.0.0/8;            # rfc1918 for ipv6 only instances'
  - '129.177.31.64/27;      # test01 IPv4'
  - '129.177.31.96/27;      # test01 IPv4'
  - '2001:700:200:915::/64; # test01 IPv6'
  - '2001:700:200:916::/64; # test01 IPv6'
  - 'fd34::/64;             # test02 IPv6'
