---
# Our internal zone
profile::dns::ns::internal_zone: "test02.uhdc.no"

# Forward zones. Only zones that are "internal". Requests for records
# in these zones will be forwarded to the authoritative DNS server
#profile::dns::ns::fw_zones:
#  internal:
#    zone: "%{hiera('profile::dns::ns::internal_zone')}"
#  frontend:
#    zone: "iaas.uio.no"

# Reverse zones. Only zones that are "internal". Requests for records
# in these zones will be forwarded to the authoritative DNS server
profile::dns::ns::ptr_zones:
  internal:
    cidr: "172.28.0.0/16"
    origin: "28.172.in-addr.arpa"
  public:
    cidr: "10.100.0.0/16"
    origin: "100.10.in-addr.arpa"
  ipv6:
    cidr: "fd34::/7"
    origin: "4.3.d.f.ip6.arpa"
