---
named_interfaces::config:
  mgmt:
    - em3
  trp:
    - bond1
  ceph:
    - bond1

#### FIXME move to common when all clusters are upgraded to mimic
profile::storage::cephosd::create_osds: true

profile::storage::fake_ssds:
  'sdb': {}
  'sdc': {}

profile::storage::cephosd::osds:
  '/dev/sdb':
    ensure: present
  '/dev/sdc':
    ensure: present
  '/dev/sdd':
    ensure: present
  '/dev/sde':
    ensure: present
  '/dev/sdf':
    ensure: present
  '/dev/sdg':
    ensure: present
