---
named_interfaces::config:
  mgmt:
    - bond0.940
  public:
    - bond0
  core:
    - bond0.940
  uib:
    - bond0.942

# network
netcfg_core_netpart:  '192.168.20'
netcfg_uib_netpart:   '192.168.22'

# ssh access
profile::firewall::pre::ssh_settings:
  source:
    - "%{::network_mgmt1}/%{::netmask_mgmt1}"
    - "%{hiera('netcfg_core_netpart')}.9" # t1-iam-login
    - "%{hiera('netcfg_core_netpart')}.10" # t2-iam-login
accounts::ssh_keys:
  'iaas_iam':
    type:    'ssh-ed25519'
    public:  'AAAAC3NzaC1lZDI1NTE5AAAAIMNVlfrsg1juBjCJe9DhDjsrV00NIbbuzdTiA/YmLiRG'

accounts::accounts:
  'iaas':
    ensure: present
    authorized_keys: [ 'iaas', 'iaas_iam']
