---
named_interfaces::config:
  mgmt:
    - eth0
  public:
    - eth1

corosync::unicast_addresses:
  - "%{hiera('netcfg_public2_netpart')}.190"
  - "%{hiera('netcfg_public2_netpart')}.191"

corosync::quorum_members:
  - "%{hiera('netcfg_public2_netpart')}.190"
  - "%{hiera('netcfg_public2_netpart')}.191"

corosync_cluster_node1:   "%{::location}-ha-test-01.%{hiera('domain_mgmt')}"
corosync_cluster_node2:   "%{::location}-ha-test-02.%{hiera('domain_mgmt')}"

corosync_cluster_vip1:    "%{hiera('netcfg_public2_netpart')}.34"  # pubtestproxy.ha
corosync_cluster_vip2:    "%{hiera('netcfg_public2_netpart')}.35"  # pubtestproxy.ha
corosync_cluster_vip3:    "%{hiera('netcfg_public2_netpart')}.243" # uibtestproxy.ha
corosync_cluster_vip4:    "%{hiera('netcfg_public2_netpart')}.244" # uibtestproxy.ha
corosync_cluster_vip5:    "%{hiera('netcfg_public2_netpart')}.245" # ssltestproxy.ha
corosync_cluster_vip6:    "%{hiera('netcfg_public2_netpart')}.198" # ssltestproxy.ha

ssl_cert_apps:            "appstest.uib.no.pem"

haproxy::global_options:
  log:          '127.0.0.1 local6 info alert'
  #nbproc:       '2'
  #cpu-map:      ['1 0', '2 2']
  maxconn:      '2000' # per core
  crt-base:     '/etc/pki/tls/certs'
