---
include:
  default:
    - profile::application::openssl

profile::application::openssl::certs:
  "star.api.%{hiera('domain_public')}":
    cn:     "*.api.%{hiera('domain_public')}"
    altnames:
      - "*.api.%{hiera('domain_public')}"
    concat: true
  "status.%{hiera('domain_public')}":
    cn:     "status.%{hiera('domain_public')}"
    concat: true
  "api.%{hiera('domain_public')}":
    cn:     "api.%{hiera('domain_public')}"
    altnames:
      - "api.%{hiera('domain_public')}"
    concat: true

#
# Example of override network backend for more nodes
#
# profile::highavailability::loadbalancing::haproxy::haproxy_balancermembers:
#   network:
#     listening_service:  'bk_network'
#     ports:              9696
#     server_names:
#       - '%{::location}-network-01'
#       - '%{::location}-network-02'
#     ipaddresses:
#       - "%{hiera('netcfg_trp_netpart')}.71"
#       - "%{hiera('netcfg_trp_netpart')}.72"
#     options:            'check'
