---
profile::openstack::resource::networks:
  public:
    name: 'public'
    admin_state_up: true
    shared: true
    tenant_name: 'openstack'
    provider_network_type: 'local'

profile::openstack::resource::subnets:
  public:
    name: 'public'
    cidr: '172.31.24.0/24'
    ip_version: '4'
    allocation_pools:
      - 'start=172.31.24.200,end=172.31.24.250'
    gateway_ip: '172.31.24.1'
    dns_nameservers:
      - '129.177.6.54'
      - '129.177.12.31'
    network_name: 'public'
    tenant_name: 'openstack'
