[INPUT]
    Name    tail
    Tag     uio_logs_5000_tail_dns_bind9
    path    /var/named/data/querylog
    db      /var/lib/fluent-bit/storage/dns_bind9.db
    Read_from_Head false

    Mem_Buf_Limit 100MB
    storage.type filesystem
    storage.pause_on_chunks_overlimit on

[FILTER]
    Name modify
    Match uio_logs_5000_tail_dns_bind9

    Add dataops.data_processor dataops-logs-dns-bind9

    Add event.module dns_bind9
    Add event.provider dns_bind9
    Add event.dataset dns_bind9.querylog

    Add data_stream.namespace prod
    Add data_stream.dataset dns_bind9.querylog

    Add service.name dns-resolver

[FILTER]
    Name nest
    Match *

    Operation nest
    Wildcard dataops.*
    Nest_under dataops
    Remove_prefix dataops.

[FILTER]
    Name nest
    Match *

    Operation nest
    Wildcard event.*
    Nest_under event
    Remove_prefix event.

[FILTER]
    Name nest
    Match *

    Operation nest
    Wildcard data_stream.*
    Nest_under data_stream
    Remove_prefix data_stream.

[FILTER]
    Name nest
    Match *

    Operation nest
    Wildcard service.*
    Nest_under service
    Remove_prefix service.
