[FILTER]
    Name modify
    Match *
    Add agent.type fluent-bit

[FILTER]
    Name sysinfo
    Match *
    Fluentbit_version_key agent.version
    Os_name_key os.name
    Os_version_key os.version
    Kernel_version_key os.kernel
    Hostname_key host.name

[FILTER]
    Name nest
    Match *

    Operation nest
    Wildcard agent.*
    Nest_under agent
    Remove_prefix agent.

[FILTER]
    Name nest
    Match *

    Operation nest
    Wildcard os.*
    Nest_under os
    Remove_prefix os.

[FILTER]
    Name nest
    Match *

    Operation nest
    Wildcard host.*
    Wildcard os*
    Nest_under host
    Remove_prefix host.

