---
include:
  default:
    - profile::application::openssl::catrust

named_interfaces::config:
  mgmt:
    - eth0
  trp:
    - eth0.912
  live:
    - eth0.912

# Add custom routing table for private network to NAT
profile::base::network::routes:
  'eth0.100':
    'ipaddress': [ '0.0.0.0', '0.0.0.0', ]
    'netmask':   [ '0.0.0.0', '0.0.0.0', ]
    'gateway':   [ "%{hiera('netcfg_priv_gateway')}", "%{hiera('netcfg_trp_gateway')}" ]
    'table':     [ 'private', 'main', ]
profile::base::network::routing_tables:
  'private':
    'table_id':  '240'
profile::base::network::rules:
  'eth0.100':
    iprule: [ "from %{hiera('netcfg_priv_network')} lookup private", ]

# Red Hat Subscription Management (RHSM)
profile::rhsm::subscription::manage: false
profile::rhsm::virtwho::manage:      false
