---
include:
  default:
    - profile::application::openssl::catrust

# Project for global image sharing
profile::openstack::resource::image_sharing::manage: false
#profile::openstack::resource::image_sharing::domain: 'default'
