---
include:
  default:
    - profile::network::dns_extra_zone

foreman_version: '1.16'

# Add in addition to mgmt.tos.uhdc.no
profile::network::dns_extra_zone::zone:
  - "%{hiera('domain_trp')}"
  - "%{hiera('domain_public')}"
#  - "%{hiera('domain_frontend')}"

# Bind utils will be installed with foreman::dns
profile::base::common::packages:
  'bind-utils': { ensure: absent }

profile::application::foreman::push_facts:    true
