---
profile::base::common::manage_lvm: true

profile::base::lvm::physical_volume:
  '/dev/vdb':
    ensure: present
    force:  true
profile::base::lvm::volume_group:
  'vg_dbbck':
    physical_volumes:
      - /dev/vdb
profile::base::lvm::logical_volume:
  'lv_dbbck':
    volume_group: 'vg_dbbck'
    fs_type:      "xfs"
    mountpath:    "/var/db/dumps"
