---
named_interfaces::config:
  mgmt:
    - em3
  trp:
    - team1

profile::base::network::network_auto_opts:
  trp:
    'defroute': 'no'
    'devicetype': 'Team'
    'team_config': >-
                   { "runner" : {  "name" : "lacp",  "active": true, "fast_rate" : true,
                   "tx_hash": ["eth", "ipv4", "ipv6"], "tx_balancer": { "name": "basic" } },
                   "link_watch" : {  "name" : "ethtool" } }

profile::base::physical::configure_bmc_nic:          true
profile::base::physical::enable_redfish_sensu_check: true
profile::monitoring::sensu::agent::checks:
  'redfish-check':
    command:      '/usr/local/bin/redfish_check.sh'
    interval:     1800
    subscribers:  ['checks']
