---
profile::base::common::manage_cron: true
profile::base::common::manage_lvm: true
profile::base::cron::crontabs:
  stats:
    hour:     '*'
    minute:   [14,29,44,59]
    command:  '/opt/himlarcli/bin/gen_stats.sh >/dev/null'
  checks:
    hour:     '*'
    minute:   '*/5'
    command:  '/opt/himlarcli/bin/check_services.sh >/dev/null'
  update_images:
    hour:     '10'
    minute:   '10'
    weekday:  '1'
    command:  '/opt/himlarcli/bin/update_images.sh >/dev/null'

profile::base::lvm::physical_volume:
  '/dev/vdb':
    ensure: present
    force:  true
profile::base::lvm::volume_group:
  'vg_opt':
    physical_volumes:
      - /dev/vdb
profile::base::lvm::logical_volume:
  'lv_opt':
    volume_group: 'vg_opt'
    fs_type:      "xfs"
    mountpath:    "/opt"
