---
profile::base::network::network_auto_opts:
  trp:
    'defroute': 'no'
    'devicetype': 'Team'
    'mtu': '9000'
    'team_config': >-
                   { "runner" : {  "name" : "lacp",  "active": true, "fast_rate" : true,
                   "tx_hash": ["eth", "ipv4", "ipv6"], "tx_balancer": { "name": "basic" } },
                   "link_watch" : {  "name" : "ethtool" } }
  ceph:
    'defroute': 'no'

profile::base::network::network_auto_bonding:
  trp:
    p4p1:
      'team_port_config': '{ "prio" : 100 }'
      'mtu': '9000'
    p4p2:
      'team_port_config': '{ "prio" : 100 }'
      'mtu': '9000'

profile::storage::cephosd::crush_parent:      'dcache'
profile::storage::cephosd::crush_parent_type: 'pod'

#profile::base::common::manage_lvm: false
#profile::base::lvm::create_lvm:    false

# sensu overrides
sensu__memory__check:     "check-memory-percent.rb -w 90 -c 95"

profile::storage::cephclient::create_extraconf: true
profile::storage::ceph_extraconf::config:
  osd_memory_target:
    'config_key'  : "osd/osd_memory_target"
    'config_value': "5368709120"
  osd_max_scrubs:
    'config_key'  : "osd/osd_max_scrubs"
    'config_value': "2"
  osd_deep_scrub_interval:
    'config_key'  : "osd/osd_deep_scrub_interval"
    'config_value': "2419200.000000"
  osd_recovery_max_active:
    'config_key'  : "osd/osd_recovery_max_active"
    'config_value': "6"
  osd_max_backfills:
    'config_key'  : "osd/osd_max_backfills"
    'config_value': "2"

profile::storage::cephpool::manage_ec_pools: true

profile::storage::ceph_ecpool::ec_pools:
  'dcache_hdd_ec_data':
    pg_num:              "2048"
    manage:              true
    allow_ec_overwrites: true
    k_data:              "10"
    m_code:              "3"
    crush_root:          "dcache"
profile::storage::cephpool::pools:
  'dcache_hdd_ec_meta':
    ensure: present
    pg_num: 512
    pgp_num: 512
profile::storage::cephpool_params::pools:
  'dcache_hdd_ec_meta':
    replicas_num:       4
    replicas_min_size:  3
    crush_rule:         "hdd-dcache"
    application_enable: 'rbd'
  'dcache_hdd_ec_data':
    application_enable: 'rbd'
    replicas_min_size:  '11'

profile::base::common::extraswap:         true
profile::base::common::extraswap_sizegb:  20
profile::base::common::extraswap_fileloc: '/var/lib/swap/swapfile'

profile::base::lvm::volume_group:
  'vg_swap':
    physical_volumes:
      - /dev/sds3
  'vg_cache1':
    physical_volumes:
      - /dev/sdq
  'vg_cache2':
    physical_volumes:
      - /dev/sdr
profile::base::lvm::logical_volume:
  'lv_swap2':
    volume_group: 'vg_swap'
    fs_type:      xfs
    size:         40G
    mountpath:    "/var/lib/swap"
  'lv_dba':
    volume_group: 'vg_cache1'
    createfs:     false
    size:         80G
  'lv_dbb':
    volume_group: 'vg_cache1'
    createfs:     false
    size:         80G
  'lv_dbc':
    volume_group: 'vg_cache1'
    createfs:     false
    size:         80G
  'lv_dbd':
    volume_group: 'vg_cache1'
    createfs:     false
    size:         80G
  'lv_dbe':
    volume_group: 'vg_cache1'
    createfs:     false
    size:         80G
  'lv_dbf':
    volume_group: 'vg_cache2'
    createfs:     false
    size:         80G
  'lv_dbg':
    volume_group: 'vg_cache2'
    createfs:     false
    size:         80G
  'lv_dbh':
    volume_group: 'vg_cache2'
    createfs:     false
    size:         80G
  'lv_dbi':
    volume_group: 'vg_cache2'
    createfs:     false
    size:         80G
  'lv_dbj':
    volume_group: 'vg_cache2'
    createfs:     false
    size:         80G
  'lv_dbk':
    volume_group: 'vg_cache2'
    createfs:     false
    size:         80G
  'lv_dbl':
    volume_group: 'vg_cache2'
    createfs:     false
    size:         80G
  'lv_dbm':
    volume_group: 'vg_cache2'
    createfs:     false
    size:         80G
  'lv_dbn':
    volume_group: 'vg_cache2'
    createfs:     false
    size:         80G
  'lv_dbo':
    volume_group: 'vg_cache2'
    createfs:     false
    size:         80G
  'lv_dbp':
    volume_group: 'vg_cache2'
    createfs:     false
    size:         80G
profile::base::lvm::physical_volume:
  '/dev/sdq':
    ensure: present
    force:  true
  '/dev/sdr':
    ensure: present
    force:  true

profile::storage::cephosd::osds:
  '/dev/sda':
    wal_device: false
    db_device:  'vg_cache1/lv_dba'
#    wal_device: 'vg_cache/lv_wala'
  '/dev/sdb':
    wal_device: false
    db_device:  'vg_cache1/lv_dbb'
#    wal_device: 'vg_cache/lv_walb'
  '/dev/sdc':
    wal_device: false
    db_device:  'vg_cache1/lv_dbc'
#    wal_device: 'vg_cache/lv_walc'
  '/dev/sdd':
    wal_device: false
    db_device:  'vg_cache1/lv_dbd'
#    wal_device: 'vg_cache/lv_wald'
  '/dev/sde':
    wal_device: false
    db_device:  'vg_cache1/lv_dbe'
#    wal_device: 'vg_cache/lv_wale'
  '/dev/sdf':
    wal_device: false
    db_device:  'vg_cache2/lv_dbf'
#    wal_device: 'vg_cache/lv_walf'
  '/dev/sdg':
    wal_device: false
    db_device:  'vg_cache2/lv_dbg'
#    wal_device: 'vg_cache/lv_walg'
  '/dev/sdh':
    wal_device: false
    db_device:  'vg_cache2/lv_dbh'
#    wal_device: 'vg_cache/lv_walh'
  '/dev/sdi':
    wal_device: false
    db_device:  'vg_cache2/lv_dbi'
#    wal_device: 'vg_cache/lv_wali'
  '/dev/sdj':
    wal_device: false
    db_device:  'vg_cache2/lv_dbj'
#    wal_device: 'vg_cache/lv_walj'
  '/dev/sdk':
    wal_device: false
    db_device:  'vg_cache2/lv_dbk'
#    wal_device: 'vg_cache/lv_walk'
  '/dev/sdl':
    wal_device: false
    db_device:  'vg_cache2/lv_dbl'
#    wal_device: 'vg_cache/lv_wall'
  '/dev/sdm':
    wal_device: false
    db_device:  'vg_cache2/lv_dbm'
#    wal_device: 'vg_cache/lv_walm'
  '/dev/sdn':
    wal_device: false
    db_device:  'vg_cache2/lv_dbn'
#    wal_device: 'vg_cache/lv_waln'
  '/dev/sdo':
    wal_device: false
    db_device:  'vg_cache2/lv_dbo'
#    wal_device: 'vg_cache/lv_walo'
  '/dev/sdp':
    wal_device: false
    db_device:  'vg_cache2/lv_dbp'
#    wal_device: 'vg_cache/lv_walo'

# Sensu
sudo::configs:
  sensu_tty:
    priority: 20
    content:  'Defaults:sensu !requiretty'
  sensu:
    priority: 25
    content:  'sensu ALL=(ALL) NOPASSWD: /opt/sensu/embedded/bin/check-smart.rb'

profile::monitoring::sensu::agent::checks:
  'check-smart':
    command:      "/usr/bin/sudo /opt/sensu/embedded/bin/check-smart.rb"
    interval:     600
    subscribers:  ['checks']

profile::monitoring::sensu::agent::plugin_gems:
  sensu-plugins-himlar:
    ensure:   '0.3.0'
    provider: 'sensu_gem'
    source:   'http://download.iaas.uio.no/uh-iaas/gem'
